import React, { createContext, useContext, useEffect, useState } from "react";
import { useLocation } from "wouter";

export type Language = "en" | "fr" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
  langPrefix: string; // e.g. "/en" or "/fr" or "/ar"
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// ─── Helpers ─────────────────────────────────────────────────────────────────

const SUPPORTED_LANGS: Language[] = ["en", "fr", "ar"];

function getLangFromPath(path: string): Language {
  const segment = path.split("/")[1] as Language;
  return SUPPORTED_LANGS.includes(segment) ? segment : "en";
}

function stripLangPrefix(path: string): string {
  const segment = path.split("/")[1];
  if (SUPPORTED_LANGS.includes(segment as Language)) {
    return path.replace(`/${segment}`, "") || "/";
  }
  return path;
}

// ─── Translation strings ────────────────────────────────────────────────────

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Navbar ──
    "nav.home": "Home",
    "nav.about": "About",
    "nav.courses": "Courses",
    "nav.groupCoaching": "Group Coaching",
    "nav.pricing": "Pricing",
    "nav.freeTest": "Free Test",
    "nav.successStories": "Success Stories",
    "nav.freeResources": "Free Resources",
    "nav.bookLesson": "Book a Lesson",
    "nav.language": "English",

    // ── Footer ──
    "footer.tagline": "Your path to English fluency — personalised coaching for Moroccan professionals and students.",
    "footer.quickLinks": "Quick Links",
    "footer.programs": "Programs",
    "footer.getInTouch": "Get in Touch",
    "footer.ielts": "IELTS Preparation",
    "footer.business": "Business English",
    "footer.group": "Group Coaching",
    "footer.conversation": "Conversation Practice",
    "footer.general": "General English",
    "footer.freeResources": "Free Resources",
    "footer.pronunciationAudit": "Free Pronunciation Audit",
    "footer.rights": "All rights reserved. Based in Tangier, Morocco.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.bookCall": "Book a Free Consultation Call",
    "footer.home": "Home",
    "footer.about": "About Mr. Ibrahim",
    "footer.courses": "Courses",
    "footer.pricing": "Pricing",
    "footer.freeTest": "Free Level Test",
    "footer.blog": "Blog",
    "footer.successStories": "Success Stories",

    // ── Home ──
    "home.hero.badge": "🇲🇦 #1 English Coach in Morocco",
    "home.hero.title": "Speak English with Confidence — Results Guaranteed",
    "home.hero.subtitle": "Personalised 1-on-1 English coaching for Moroccan professionals and students. IELTS, Business English, Conversation Fluency — real results in 8 weeks.",
    "home.hero.cta1": "Book Free Consultation Call",
    "home.hero.cta2": "View Programs & Pricing",
    "home.hero.students": "100+ Students",
    "home.hero.rating": "4.9★ Rating",
    "home.hero.weeks": "Results in 8 Weeks",
    "home.hero.guarantee": "Results Guarantee",
    "home.hero.badge2": "TESOL-Certified Coach · Based in Morocco",
    "home.hero.h1a": "From Frozen to Fluent.",
    "home.hero.h1b": "Achieve 7.5+ IELTS",
    "home.hero.h1c": "in 8 Weeks.",
    "home.hero.bilingual": "Struggling to speak English fluently?",
    "home.hero.desc": "Morocco's outcome-focused English coach. Mr. Ibrahim K. delivers real results — not just lessons.",
    "home.hero.desc2": "90% of students reach their goal in 8 weeks.",
    "home.hero.guarantee2": "Results Guaranteed — or we coach you for free until you succeed",
    "home.hero.noCommit": "No commitment required · Free 10-min consultation · Results guaranteed",
    "home.hero.studentsCoached": "Students Coached",
    "home.hero.reachGoal": "Reach Their Goal",
    "home.hero.avgRating": "Average Rating",
    "home.hero.yearsExp": "Years Experience",

    "home.results.ieltsBands": "Average IELTS Improvement",
    "home.results.achieve": "Students Achieve Target Score",
    "home.results.time": "Average Time to Results",
    "home.results.satisfaction": "Student Satisfaction",

    "home.intro.title": "Stop Buying Lessons. Start Buying Results.",
    "home.intro.desc": "Most English teachers sell you hours. Fluentry sells you outcomes. Mr. Ibrahim K. works with a select group of motivated students in Morocco to deliver one thing:",
    "home.intro.strong": "measurable, guaranteed progress",
    "home.intro.desc2": "— whether that's an IELTS band score, a promotion, or the confidence to lead meetings in English.",
    "home.intro.quote": "\"English isn't just grammar and vocabulary. It's confidence, clarity, and connection — and I guarantee you'll feel all three.\"",
    "home.intro.quoteAuthor": "— Mr. Ibrahim K., TESOL-Certified Coach & Founder of Fluentry",

    "home.programs.title": "Outcome-Based Programs",
    "home.programs.subtitle": "Not just lessons — complete transformation programs with clear goals, structured milestones, and a results guarantee.",
    "home.programs.ielts.badge": "MOST POPULAR",
    "home.programs.ielts.title": "8-Week IELTS Accelerator",
    "home.programs.ielts.for": "For students seeking to study abroad",
    "home.programs.ielts.desc": "Achieve 7.5+ band score in 8 weeks with our proven methodology. Personalized study plan, weekly mock tests, and direct feedback on all 4 skills.",
    "home.programs.ielts.price": "12,000 MAD",
    "home.programs.ielts.priceNote": "Full 8-week program · Results guaranteed",
    "home.programs.ielts.guarantee": "Money-back guarantee if you don't reach your target",
    "home.programs.business.badge": "HIGH INCOME",
    "home.programs.business.title": "12-Week Business English Mastery",
    "home.programs.business.for": "For professionals in Casablanca & Rabat",
    "home.programs.business.desc": "Lead international meetings, write compelling emails, and present with authority. Designed for professionals in finance, tech, and management.",
    "home.programs.business.price": "15,000 MAD",
    "home.programs.business.priceNote": "Full 12-week program · Results guaranteed",
    "home.programs.business.guarantee": "Guaranteed fluency for professional settings",
    "home.programs.vip.badge": "VIP ELITE",
    "home.programs.vip.title": "VIP Concierge Coaching",
    "home.programs.vip.for": "For executives & serious investors",
    "home.programs.vip.desc": "Unlimited 1-on-1 sessions, 24/7 WhatsApp access, fully bespoke curriculum, and direct involvement in every aspect of your English journey.",
    "home.programs.vip.price": "25,000 MAD",
    "home.programs.vip.priceNote": "Complete VIP program · Unlimited access",
    "home.programs.vip.guarantee": "Full results guarantee — no exceptions",
    "home.programs.vip.cta": "Apply for VIP Program",
    "home.programs.flexible": "Prefer a flexible monthly plan?",
    "home.programs.viewPricing": "View all pricing options →",
    "home.programs.bookCall": "Book Free Consultation Call",

    "home.why.title": "Why Fluentry is Different",
    "home.why.subtitle": "There are hundreds of English teachers in Morocco. Here is why serious learners choose Fluentry.",
    "home.why.method.title": "The Fluency Bridge Method™",
    "home.why.method.desc": "Our proprietary conversation-first, confidence-building approach. We don't teach grammar rules — we build real communication skills that transfer to real life.",
    "home.why.guarantee.title": "Results Guarantee",
    "home.why.guarantee.desc": "If you don't achieve your target IELTS score or fluency goal within the program duration, we continue coaching you for free until you do. Zero risk.",
    "home.why.morocco.title": "Morocco-Specific Expertise",
    "home.why.morocco.desc": "Mr. Ibrahim K. understands the exact challenges Moroccan learners face — from French interference to Arabic pronunciation patterns — and addresses them directly.",
    "home.why.table.feature": "Feature",
    "home.why.table.fluentry": "Fluentry",
    "home.why.table.typical": "Typical Tutor",
    "home.why.table.outcome": "Outcome-based programs",
    "home.why.table.outcomeF": "✅ Yes",
    "home.why.table.outcomeT": "❌ Hourly lessons",
    "home.why.table.resultsG": "Results guarantee",
    "home.why.table.resultsFY": "✅ Yes",
    "home.why.table.resultsTN": "❌ No",
    "home.why.table.moroccan": "Morocco-specific curriculum",
    "home.why.table.moroccanF": "✅ Yes",
    "home.why.table.moroccanT": "❌ Generic",
    "home.why.table.tesol": "TESOL-certified coach",
    "home.why.table.tesolF": "✅ Yes",
    "home.why.table.tesolT": "⚠️ Often not",
    "home.why.table.tracking": "Structured progress tracking",
    "home.why.table.trackingF": "✅ Yes",
    "home.why.table.trackingT": "❌ No",
    "home.why.table.method": "Fluency Bridge Method™",
    "home.why.table.methodF": "✅ Exclusive",
    "home.why.table.methodT": "❌ No",

    "home.how.title": "How It Works",
    "home.how.step1.title": "Book a Free Consultation Call",
    "home.how.step1.desc": "10 minutes with Mr. Ibrahim to discuss your goals, current level, and the right program for you.",
    "home.how.step2.title": "Get Your Custom Roadmap",
    "home.how.step2.desc": "Receive a personalized week-by-week plan with clear milestones and measurable outcomes.",
    "home.how.step3.title": "Achieve Your Goal",
    "home.how.step3.desc": "Follow the program, track your progress, and reach your target — guaranteed.",
    "home.how.cta": "Book Your Free Consultation Call",

    "home.courses.title": "All Course Offerings",
    "home.courses.subtitle": "Whether you're a student, professional, or lifelong learner, we have a program for you.",
    "home.courses.general.title": "General English",
    "home.courses.general.desc": "Build a strong foundation in speaking, listening, reading, and writing.",
    "home.courses.business.title": "Business English",
    "home.courses.business.desc": "Master professional communication for meetings, emails, and presentations.",
    "home.courses.ielts.title": "IELTS & TOEFL Prep",
    "home.courses.ielts.desc": "Achieve your target score with focused test strategies and practice.",
    "home.courses.conversation.title": "Conversation Practice",
    "home.courses.conversation.desc": "Improve fluency and confidence through natural, engaging conversations.",
    "home.courses.learnMore": "Learn More",

    "home.article.badge": "Featured Article",
    "home.article.title": "Latest from Fluentry",
    "home.article.h3": "The Unspoken Passport: Why English Still Shapes the World",
    "home.article.desc": "Explore how English connects cultures, careers, and opportunities in our global era. A thoughtful reflection on the enduring significance of English in the modern world.",
    "home.article.by": "By Mr. Ibrahim K.",
    "home.article.read": "5 min read",
    "home.article.readArticle": "Read Article",

    "home.blog.badge": "English Learning Blog",
    "home.blog.title": "Expert Tips & Strategies",
    "home.blog.subtitle": "Learn from TESOL-certified coach Mr. Ibrahim K. Practical advice to help you master English faster.",
    "home.blog.viewAll": "View All Blog Posts",
    "home.blog.readMore": "Read More",

    "home.cta.title": "Ready to Stop Struggling and Start Achieving?",
    "home.cta.subtitle": "Book a free 10-minute strategy call. No commitment, no pressure — just a clear plan to reach your English goals.",
    "home.cta.guarantee": "Results guaranteed — or we coach you for free",
    "home.cta.button": "Book Your Free Consultation Call",
    "home.cta.viewPrograms": "View All Programs",
    "home.cta.note": "Free 10-min call · No commitment · 100% in English or Darija",

    // ── About ──
    "about.hero.badge": "TESOL-Certified · Based in Morocco",
    "about.hero.title": "Meet Mr. Ibrahim K.",
    "about.hero.subtitle": "Morocco's outcome-focused English coach — helping students and professionals achieve real, measurable results since 2022.",
    "about.hero.cta1": "Book Free Consultation Call",
    "about.hero.cta2": "Take Free Level Test",
    "about.hero.role": "TESOL-Certified English Coach",
    "about.hero.location": "Tangier, Morocco 🇲🇦",
    "about.guarantee": "Results Guaranteed on all signature programs — if you don't reach your goal, Mr. Ibrahim coaches you for free until you do.",
    "about.story.title": "The Story Behind Fluentry",
    "about.story.quote": "\"Fluency comes from confidence, not perfection. My goal is to make English learning practical, enjoyable, and personal to every student.\"",
    "about.story.quoteBy": "— Mr. Ibrahim K.",
    "about.story.p1": "Mr. Ibrahim K. is a TESOL-certified English language coach with a Bachelor's degree in English Studies and over three years of experience teaching learners across Morocco and internationally.",
    "about.story.p2": "He currently teaches English at a private school in Morocco while also running Fluentry — his online coaching practice dedicated to helping motivated students and professionals achieve specific, measurable English goals.",
    "about.story.p3": "What makes Mr. Ibrahim different is his deep understanding of the unique challenges Moroccan learners face — the interference of French and Darija, the difficulty of English sounds that don't exist in Arabic, and the confidence barrier that stops so many people from speaking even when they know the grammar.",
    "about.story.p4": "Fluentry was built on a simple belief: students deserve to pay for results, not just hours. Every program is structured around a clear outcome — backed by a results guarantee.",
    "about.credentials.title": "Professional Qualifications",
    "about.method.badge": "Proprietary Methodology",
    "about.method.title": "The Fluency Bridge Method™",
    "about.method.subtitle": "A conversation-first, confidence-building approach that bridges the gap between knowing English and using it naturally — developed specifically for Moroccan learners.",
    "about.who.title": "Who Mr. Ibrahim Teaches",
    "about.who.subtitle": "Students, professionals, and lifelong learners from across Morocco — online and in Tangier.",
    "about.testimonials.title": "What Students Say",
    "about.mission.title": "Our Mission",
    "about.mission.text": "To provide accessible, high-quality, and personalised online English coaching in Morocco that transforms learners into confident, natural communicators — ready to thrive in a global environment. Every student deserves to pay for results, not just hours.",
    "about.cta.title": "Ready to Work with Mr. Ibrahim?",
    "about.cta.subtitle": "Book a free 10-minute strategy call. No commitment, no pressure — just a clear plan to reach your English goals.",
    "about.cta.button": "Book Free Consultation Call",
    "about.cta.viewPricing": "View Programs & Pricing",
    "about.cta.guarantee": "Results guaranteed on all signature programs",

    // ── Courses ──
    "courses.title": "Our English Programs",
    "courses.subtitle": "Personalised programs designed for Moroccan learners — from beginners to advanced professionals.",
    "courses.hero.badge": "Results Guaranteed on All Signature Programs",
    "courses.hero.title": "Programs Built Around Your Goal",
    "courses.hero.subtitle": "Every Fluentry program is structured around a specific, measurable outcome. You know exactly what you'll achieve — and we guarantee it.",
    "courses.stats.ielts": "Average IELTS Improvement",
    "courses.stats.achieve": "Students Achieve Their Goal",
    "courses.stats.time": "Average Time to Results",
    "courses.stats.satisfaction": "Satisfaction Guaranteed",
    "courses.choose.title": "Choose Your Program",
    "courses.choose.subtitle": "Not sure which program is right for you? Take the free level test or book a free 10-minute strategy call — Mr. Ibrahim will recommend the best fit for your goals.",
    "courses.ielts.title": "IELTS & TOEFL Preparation",
    "courses.ielts.desc": "Achieve your target band score — guaranteed",
    "courses.business.title": "Business English Mastery",
    "courses.business.desc": "Lead meetings, write emails, present with authority",
    "courses.conversation.title": "Conversation & Fluency",
    "courses.conversation.desc": "Stop freezing — start speaking naturally",
    "courses.general.title": "General English",
    "courses.general.desc": "Build a strong foundation from scratch",
    "courses.forWho": "WHO IT'S FOR",
    "courses.achieve": "WHAT YOU'LL ACHIEVE",
    "courses.bookCall": "Book Free Consultation Call",
    "courses.startCoaching": "Start Coaching",
    "courses.program": "Program",
    "courses.investment": "Investment",
    "courses.cta.title": "Not Sure Which Program is Right for You?",
    "courses.cta.subtitle": "Book a free 10-minute strategy call. Mr. Ibrahim will assess your level, understand your goals, and recommend the best program for your situation.",
    "courses.cta.button": "Book Free Consultation Call on WhatsApp",
    "courses.cta.note": "Free 10-min call · No commitment · Personalised recommendation",

    // ── Pricing ──
    "pricing.title": "Choose Your Plan",
    "pricing.subtitle": "Transparent pricing. No hidden fees. Cancel anytime.",
    "pricing.perHour": "per hour",
    "pricing.perMonth": "per month",
    "pricing.mostPopular": "Most Popular",
    "pricing.bestValue": "Best Value",
    "pricing.getStarted": "Get Started",
    "pricing.bookCall": "Book Free Consultation Call",
    "pricing.freeConsult": "Free 10-min consultation · No commitment",
    "pricing.saveVsStandard": "Save vs Standard",
    "pricing.standard": "Standard",
    "pricing.intensive": "Intensive",
    "pricing.accelerator": "Accelerator",
    "pricing.hero.urgency": "Only 3 spots available this month — prices may increase in April",
    "pricing.hero.h1a": "The More You Practise,",
    "pricing.hero.h1b": "The Less You Pay Per Hour.",
    "pricing.hero.desc": "Unlike language schools that charge a flat rate regardless of commitment, Fluentry rewards students who are serious. Book more sessions — pay less per hour — progress faster.",
    "pricing.hero.studentsCoached": "100+ Students Coached",
    "pricing.hero.rating": "4.9★ Average Rating",
    "pricing.hero.results": "Results in 8 Weeks",
    "pricing.hero.guarantee": "Results Guaranteed",
    "pricing.plans.badge": "Choose Your Pace",
    "pricing.plans.title": "All Plans — 1-on-1 with Mr. Ibrahim",
    "pricing.plans.subtitle": "Every plan includes private sessions, a personalised study plan, and WhatsApp support. The more sessions you book, the lower your hourly rate — and the faster you reach fluency.",

    // ── Pricing (extended) ──
    "pricing.hero.subtitle": "Unlike language schools that charge a flat rate regardless of commitment, Fluentry rewards students who are serious. Book more sessions — pay less per hour — progress faster.",
    "pricing.trust.students": "100+ Students Coached",
    "pricing.trust.rating": "4.9★ Average Rating",
    "pricing.trust.results": "Results in 8 Weeks",
    "pricing.trust.guarantee": "Results Guaranteed",
    "pricing.plan.standard": "Standard",
    "pricing.plan.intensive": "Intensive",
    "pricing.plan.accelerator": "Accelerator",
    "pricing.plans.eyebrow": "Choose Your Pace",
    "pricing.ratePerSession": "Rate per session",
    "pricing.standard.sessions": "8 sessions/month · 2 per week",
    "pricing.standard.f1": "2 × 1-hour private sessions/week",
    "pricing.standard.f2": "Personalised lesson plan",
    "pricing.standard.f3": "WhatsApp support",
    "pricing.standard.f4": "Speaking & Listening feedback",
    "pricing.standard.f5": "Monthly progress check-in",
    "pricing.standard.nudge": "💡 Upgrade to Intensive and save 80 MAD/month",
    "pricing.noCommit": "Free 10-min call first · No commitment",
    "pricing.intensive.badge": "⭐ MOST POPULAR — BEST VALUE",
    "pricing.intensive.sessions": "16 sessions/month · 4 per week",
    "pricing.intensive.savings": "You save 80 MAD/month vs paying Standard rate for 16 sessions",
    "pricing.intensive.f1": "4 × 1-hour private sessions/week",
    "pricing.intensive.f2": "Personalised lesson plan",
    "pricing.intensive.f3": "WhatsApp support",
    "pricing.intensive.f4": "Full 4-skills feedback",
    "pricing.intensive.f5": "IELTS study plan (if applicable)",
    "pricing.intensive.f6": "Email & presentation coaching",
    "pricing.intensive.f7": "Bi-weekly progress review",
    "pricing.intensive.social": "🔥 7 out of 10 students choose this plan",
    "pricing.intensive.cta": "Get Started — Best Value",
    "pricing.accelerator.badge": "⚡ FASTEST RESULTS",
    "pricing.accelerator.sessions": "24 sessions/month · 6 per week",
    "pricing.accelerator.savings": "You save 360 MAD/month vs paying Standard rate for 24 sessions",
    "pricing.accelerator.f1": "6 × 1-hour private sessions/week",
    "pricing.accelerator.f2": "Personalised lesson plan",
    "pricing.accelerator.f3": "WhatsApp support",
    "pricing.accelerator.f4": "Full 4-skills feedback",
    "pricing.accelerator.f5": "Personalised IELTS study plan",
    "pricing.accelerator.f6": "Business communication curriculum",
    "pricing.accelerator.f7": "Meeting & negotiation English",
    "pricing.accelerator.f8": "Priority scheduling",
    "pricing.accelerator.f9": "Weekly progress review",
    "pricing.accelerator.scarcity": "⚠️ Only 2 Accelerator spots available this month",
    "pricing.accelerator.cta": "Claim My Spot",
    "pricing.payPerLesson.title": "Pay-Per-Lesson",
    "pricing.payPerLesson.desc": "No commitment · 80 MAD/session",
    "pricing.bookNow": "Book Now",
    "pricing.group.title": "Group Study",
    "pricing.group.desc": "200 MAD/month · 30 MAD/session",
    "pricing.group.cta": "Join Group",
    "pricing.compare.title": "How Fluentry Compares to Other Options",
    "pricing.compare.option": "Option",
    "pricing.compare.costHr": "Cost/hr",
    "pricing.compare.oneOnOne": "1-on-1?",
    "pricing.compare.personalised": "Personalised?",
    "pricing.compare.school": "Language school (Morocco)",
    "pricing.compare.preply": "Preply / iTalki tutor",
    "pricing.compare.apps": "Duolingo / Apps",
    "pricing.compare.fluentry": "Fluentry (Intensive)",
    "pricing.compare.note": "Private, personalised coaching at a fraction of what language schools charge.",
    "pricing.programs.eyebrow": "Goal-Focused",
    "pricing.programs.title": "Structured Programs",
    "pricing.programs.subtitle": "Have a specific target — an IELTS band score or professional fluency? These fixed-duration programs include a clear roadmap, a results guarantee, and the Intensive hourly rate built in.",
    "pricing.ielts.eyebrow": "IELTS Prep",
    "pricing.ielts.title": "8-Week IELTS Program",
    "pricing.ielts.sessions": "2 sessions/week · 16 sessions total",
    "pricing.ielts.desc": "16 private sessions over 8 weeks, focused entirely on IELTS. All four sections covered with practice tests and detailed feedback every week. Guaranteed band improvement.",
    "pricing.ielts.f1": "16 × 1-hour private sessions",
    "pricing.ielts.f2": "All 4 IELTS sections: L, R, W, S",
    "pricing.ielts.f3": "Personalised IELTS study plan",
    "pricing.ielts.f4": "Mock tests with band-score feedback",
    "pricing.ielts.f5": "WhatsApp support throughout",
    "pricing.ielts.f6": "Results guarantee included",
    "pricing.business.eyebrow": "Business English",
    "pricing.business.title": "12-Week Business English",
    "pricing.business.sessions": "2 sessions/week · 24 sessions total",
    "pricing.business.desc": "24 private sessions over 12 weeks, focused on professional English. Master emails, meetings, presentations, and the vocabulary you use at work — in Casablanca, Rabat, or anywhere.",
    "pricing.business.f1": "24 × 1-hour private sessions",
    "pricing.business.f2": "Business communication curriculum",
    "pricing.business.f3": "Professional email writing",
    "pricing.business.f4": "Meeting & negotiation English",
    "pricing.business.f5": "Presentation coaching",
    "pricing.business.f6": "WhatsApp support throughout",
    "pricing.included.title": "What Every Session Includes",
    "pricing.included.goal.title": "Goal-Focused Practice",
    "pricing.included.goal.desc": "Every session is built around your specific goal — IELTS, business, or fluency.",
    "pricing.included.feedback.title": "Real-Time Feedback",
    "pricing.included.feedback.desc": "Instant corrections on pronunciation, grammar, and vocabulary as you speak.",
    "pricing.included.whatsapp.title": "WhatsApp Support",
    "pricing.included.whatsapp.desc": "Ask questions and get feedback between sessions, any time.",
    "pricing.included.progress.title": "Progress Tracking",
    "pricing.included.progress.desc": "Monthly reports showing exactly how far you've come and what's next.",
    "pricing.testimonials.title": "What Students Say",
    "pricing.faq.title": "Common Questions",
    "pricing.cta.guarantee": "Results Guaranteed — or we coach you for free",
    "pricing.cta.title": "Not Sure Which Plan Is Right for You?",
    "pricing.cta.subtitle": "Book a free 10-minute call with Mr. Ibrahim. He will listen to your goals and recommend the exact plan that fits your schedule and budget.",
    "pricing.cta.urgency": "⏳ Only 3 spots open this month — prices may increase in April",
    "pricing.cta.button": "Book Free Consultation Call",
    "pricing.cta.freeTest": "Take Free Level Test First",

    // ── Courses (extended) ──
    "courses.grid.title": "Choose Your Program",
    "courses.grid.subtitle": "Not sure which program is right for you? Take the free level test or book a free 10-minute strategy call — Mr. Ibrahim will recommend the best fit for your goals.",
    "courses.card.whoFor": "Who it's for",
    "courses.card.achieve": "What you'll achieve",
    "courses.card.program": "Program",
    "courses.sessions.title": "What Every Session Includes",
    "courses.sessions.focus.title": "Personalised Focus",
    "courses.sessions.focus.desc": "Each session is built around your specific goals, level, and the challenges you face as a Moroccan learner.",
    "courses.sessions.progress.title": "Progress Tracking",
    "courses.sessions.progress.desc": "Clear milestones and regular check-ins so you always know exactly how far you've come and what's next.",
    "courses.sessions.schedule.title": "Flexible Scheduling",
    "courses.sessions.schedule.desc": "Sessions via Google Meet. Reschedule up to 24 hours in advance. Your time, your pace.",
    "courses.testimonials.title": "Student Results",
    "courses.cta.freeTest": "Take the Free Level Test",
    "courses.cta.bookCall": "Book Free Consultation Call",

    // ── Free Test ──
    "freeTest.title": "Free English Level Test",
    "freeTest.subtitle": "Find out your exact English level in 10 minutes. Get a personalised report with recommendations.",
    "freeTest.start": "Start Free Test",

    // ── Success Stories ──
    "success.title": "Student Success Stories",
    "success.subtitle": "Real results from real Moroccan students who transformed their English.",

    // ── Free Resources ──
    "resources.title": "Free English Resources",
    "resources.subtitle": "Exercises, guides, and tools to help you improve your English — completely free.",

    // ── Common ──
    "common.learnMore": "Learn More",
    "common.bookCall": "Book Free Consultation Call",
    "common.freeCall": "Free 10-min call · No commitment",
    "common.whatsapp": "WhatsApp",
    "common.readMore": "Read More",
    "common.viewAll": "View All",
    "common.download": "Download Free",
    "common.startNow": "Start Now",
    "common.perMonth": "/month",
    "common.perHour": "/hour",
    "common.save": "Save",

    // ── Testimonials ──
    "testimonials.title": "Trusted by Learners Across Morocco",
    "testimonials.subtitle": "Real stories and real results from students who transformed their English with Fluentry.",
    "testimonials.1.name": "Fatima Z.",
    "testimonials.1.location": "IELTS Student, Casablanca",
    "testimonials.1.quote": "Ibrahim's coaching completely changed how I approach English. I went from translating every word to actually thinking in English. My IELTS score improved by 1.5 bands!",
    "testimonials.2.name": "Youssef B.",
    "testimonials.2.location": "Marketing Manager, Rabat",
    "testimonials.2.quote": "As a business professional, I needed to improve my presentation skills fast. Ibrahim's Business English course gave me the confidence to lead international meetings.",
    "testimonials.3.name": "Amina K.",
    "testimonials.3.location": "University Student, Tangier",
    "testimonials.3.quote": "The free resources are amazing! The idiom guide and listening exercises helped me so much with my daily practice. It's the best place to learn English in Morocco.",
    "testimonials.4.name": "Mehdi L.",
    "testimonials.4.location": "Software Developer, Marrakech",
    "testimonials.4.quote": "I was stuck at an intermediate level for years. The personalized 1-on-1 sessions helped me break through that plateau. I can finally communicate complex ideas clearly.",
    "testimonials.5.name": "Salma C.",
    "testimonials.5.location": "TOEFL Student, Fes",
    "testimonials.5.quote": "The speaking practice was invaluable. Mr. Ibrahim is patient and knows exactly how to correct pronunciation for Arabic speakers. I scored 28/30 on the TOEFL speaking section!",

    // ── Newsletter ──
    "newsletter.title": "Get Weekly English Tips",
    "newsletter.subtitle": "Join hundreds of students receiving free English learning tips, grammar explanations, and study strategies every week.",
    "newsletter.placeholder": "Enter your email",
    "newsletter.button": "Subscribe Free",
    "newsletter.subscribing": "Subscribing...",
    "newsletter.disclaimer": "No spam. Unsubscribe anytime. 100% free forever.",
    "newsletter.error": "Please enter a valid email address",
    "newsletter.success": "Thanks for subscribing! Check your email for confirmation.",

    // ── Blog posts (Home) ──
    "home.blog.post1.title": "Online English Classes for Moroccans",
    "home.blog.post1.excerpt": "Compare prices and methods to find the best way to learn English online.",
    "home.blog.post1.category": "Learning Guide",
    "home.blog.post1.readTime": "12 min",
    "home.blog.post2.title": "From A2 to B1 in 6 Months",
    "home.blog.post2.excerpt": "A practical 6-month plan with weekly schedule to improve your English.",
    "home.blog.post2.category": "Learning Plan",
    "home.blog.post2.readTime": "10 min",
    "home.blog.post3.title": "15 Best Apps & Websites for Learning English",
    "home.blog.post3.excerpt": "Discover the top digital tools for vocabulary, listening, and reading.",
    "home.blog.post3.category": "Tool Review",
    "home.blog.post3.readTime": "14 min",
    "home.blog.post4.title": "5 Challenges Moroccan Learners Face",
    "home.blog.post4.excerpt": "Understand the unique obstacles and practical solutions for Moroccan learners.",
    "home.blog.post4.category": "Learning Insights",
    "home.blog.post4.readTime": "11 min",
  },

  fr: {
    // ── Navbar ──
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.courses": "Cours",
    "nav.groupCoaching": "Coaching de groupe",
    "nav.pricing": "Tarifs",
    "nav.freeTest": "Test gratuit",
    "nav.successStories": "Témoignages",
    "nav.freeResources": "Ressources gratuites",
    "nav.bookLesson": "Réserver un cours",
    "nav.language": "Français",

    // ── Footer ──
    "footer.tagline": "Votre chemin vers la maîtrise de l'anglais — coaching personnalisé pour les professionnels et étudiants marocains.",
    "footer.quickLinks": "Liens rapides",
    "footer.programs": "Programmes",
    "footer.getInTouch": "Nous contacter",
    "footer.ielts": "Préparation IELTS",
    "footer.business": "Anglais des affaires",
    "footer.group": "Coaching de groupe",
    "footer.conversation": "Pratique de conversation",
    "footer.general": "Anglais général",
    "footer.freeResources": "Ressources gratuites",
    "footer.pronunciationAudit": "Audit de prononciation gratuit",
    "footer.rights": "Tous droits réservés. Basé à Tanger, Maroc.",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "footer.bookCall": "Réserver un appel stratégique gratuit",
    "footer.home": "Accueil",
    "footer.about": "À propos de M. Ibrahim",
    "footer.courses": "Cours",
    "footer.pricing": "Tarifs",
    "footer.freeTest": "Test de niveau gratuit",
    "footer.blog": "Blog",
    "footer.successStories": "Témoignages",

    // ── Home ──
    "home.hero.badge": "🇲🇦 Coach d'anglais n°1 au Maroc",
    "home.hero.title": "Parlez anglais avec confiance — Résultats garantis",
    "home.hero.subtitle": "Coaching anglais personnalisé en tête-à-tête pour les professionnels et étudiants marocains. IELTS, Anglais des affaires, Fluidité conversationnelle — de vrais résultats en 8 semaines.",
    "home.hero.cta1": "Appel stratégique gratuit",
    "home.hero.cta2": "Voir les programmes et tarifs",
    "home.hero.students": "100+ Étudiants",
    "home.hero.rating": "Note 4,9★",
    "home.hero.weeks": "Résultats en 8 semaines",
    "home.hero.guarantee": "Garantie résultats",
    "home.hero.badge2": "Coach certifié TESOL · Basé au Maroc",
    "home.hero.h1a": "Du blocage à la fluidité.",
    "home.hero.h1b": "Atteignez 7,5+ à l'IELTS",
    "home.hero.h1c": "en 8 semaines.",
    "home.hero.bilingual": "Vous bloquez quand vous parlez anglais ?",
    "home.hero.desc": "Le coach d'anglais axé sur les résultats au Maroc. M. Ibrahim K. délivre de vrais résultats — pas seulement des cours.",
    "home.hero.desc2": "90% des étudiants atteignent leur objectif en 8 semaines.",
    "home.hero.guarantee2": "Résultats garantis — ou nous vous coachons gratuitement jusqu'à votre réussite",
    "home.hero.noCommit": "Sans engagement · Consultation gratuite 10 min · Résultats garantis",
    "home.hero.studentsCoached": "Étudiants coachés",
    "home.hero.reachGoal": "Atteignent leur objectif",
    "home.hero.avgRating": "Note moyenne",
    "home.hero.yearsExp": "Années d'expérience",

    "home.results.ieltsBands": "Amélioration IELTS moyenne",
    "home.results.achieve": "Étudiants atteignant leur score cible",
    "home.results.time": "Délai moyen pour les résultats",
    "home.results.satisfaction": "Satisfaction des étudiants",

    "home.intro.title": "Arrêtez d'acheter des heures. Achetez des résultats.",
    "home.intro.desc": "La plupart des professeurs d'anglais vous vendent des heures. Fluentry vous vend des résultats. M. Ibrahim K. travaille avec un groupe sélect d'étudiants motivés au Maroc pour délivrer une chose :",
    "home.intro.strong": "des progrès mesurables et garantis",
    "home.intro.desc2": "— que ce soit un score IELTS, une promotion, ou la confiance pour diriger des réunions en anglais.",
    "home.intro.quote": "\"L'anglais n'est pas seulement de la grammaire et du vocabulaire. C'est la confiance, la clarté et la connexion — et je vous garantis que vous ressentirez les trois.\"",
    "home.intro.quoteAuthor": "— M. Ibrahim K., Coach certifié TESOL & Fondateur de Fluentry",

    "home.programs.title": "Programmes axés sur les résultats",
    "home.programs.subtitle": "Pas seulement des cours — des programmes de transformation complets avec des objectifs clairs, des jalons structurés et une garantie de résultats.",
    "home.programs.ielts.badge": "LE PLUS POPULAIRE",
    "home.programs.ielts.title": "Accélérateur IELTS 8 semaines",
    "home.programs.ielts.for": "Pour les étudiants souhaitant étudier à l'étranger",
    "home.programs.ielts.desc": "Atteignez 7,5+ en 8 semaines avec notre méthodologie éprouvée. Plan d'étude personnalisé, tests blancs hebdomadaires et feedback direct sur les 4 compétences.",
    "home.programs.ielts.price": "12 000 MAD",
    "home.programs.ielts.priceNote": "Programme complet 8 semaines · Résultats garantis",
    "home.programs.ielts.guarantee": "Remboursement garanti si vous n'atteignez pas votre objectif",
    "home.programs.business.badge": "REVENUS ÉLEVÉS",
    "home.programs.business.title": "Maîtrise de l'anglais des affaires 12 semaines",
    "home.programs.business.for": "Pour les professionnels à Casablanca & Rabat",
    "home.programs.business.desc": "Dirigez des réunions internationales, rédigez des e-mails percutants et présentez avec autorité. Conçu pour les professionnels en finance, tech et management.",
    "home.programs.business.price": "15 000 MAD",
    "home.programs.business.priceNote": "Programme complet 12 semaines · Résultats garantis",
    "home.programs.business.guarantee": "Fluidité professionnelle garantie",
    "home.programs.vip.badge": "VIP ÉLITE",
    "home.programs.vip.title": "Coaching VIP Concierge",
    "home.programs.vip.for": "Pour les dirigeants & investisseurs sérieux",
    "home.programs.vip.desc": "Sessions illimitées en tête-à-tête, accès WhatsApp 24/7, programme entièrement sur mesure et implication directe dans chaque aspect de votre parcours.",
    "home.programs.vip.price": "25 000 MAD",
    "home.programs.vip.priceNote": "Programme VIP complet · Accès illimité",
    "home.programs.vip.guarantee": "Garantie résultats complète — sans exception",
    "home.programs.vip.cta": "Postuler au programme VIP",
    "home.programs.flexible": "Préférez un forfait mensuel flexible ?",
    "home.programs.viewPricing": "Voir toutes les options tarifaires →",
    "home.programs.bookCall": "Appel stratégique gratuit",

    "home.why.title": "Pourquoi Fluentry est différent",
    "home.why.subtitle": "Il y a des centaines de professeurs d'anglais au Maroc. Voici pourquoi les apprenants sérieux choisissent Fluentry.",
    "home.why.method.title": "La méthode Fluency Bridge™",
    "home.why.method.desc": "Notre approche propriétaire axée sur la conversation et la confiance. Nous n'enseignons pas les règles de grammaire — nous construisons de vraies compétences de communication.",
    "home.why.guarantee.title": "Garantie de résultats",
    "home.why.guarantee.desc": "Si vous n'atteignez pas votre score IELTS cible ou votre objectif de fluidité dans la durée du programme, nous continuons à vous coacher gratuitement. Zéro risque.",
    "home.why.morocco.title": "Expertise spécifique au Maroc",
    "home.why.morocco.desc": "M. Ibrahim K. comprend les défis exacts des apprenants marocains — de l'interférence du français aux schémas de prononciation arabes — et les aborde directement.",
    "home.why.table.feature": "Caractéristique",
    "home.why.table.fluentry": "Fluentry",
    "home.why.table.typical": "Tuteur classique",
    "home.why.table.outcome": "Programmes axés sur les résultats",
    "home.why.table.outcomeF": "✅ Oui",
    "home.why.table.outcomeT": "❌ Cours à l'heure",
    "home.why.table.resultsG": "Garantie de résultats",
    "home.why.table.resultsFY": "✅ Oui",
    "home.why.table.resultsTN": "❌ Non",
    "home.why.table.moroccan": "Programme spécifique au Maroc",
    "home.why.table.moroccanF": "✅ Oui",
    "home.why.table.moroccanT": "❌ Générique",
    "home.why.table.tesol": "Coach certifié TESOL",
    "home.why.table.tesolF": "✅ Oui",
    "home.why.table.tesolT": "⚠️ Souvent non",
    "home.why.table.tracking": "Suivi structuré des progrès",
    "home.why.table.trackingF": "✅ Oui",
    "home.why.table.trackingT": "❌ Non",
    "home.why.table.method": "Méthode Fluency Bridge™",
    "home.why.table.methodF": "✅ Exclusif",
    "home.why.table.methodT": "❌ Non",

    "home.how.title": "Comment ça marche",
    "home.how.step1.title": "Réservez un appel stratégique gratuit",
    "home.how.step1.desc": "10 minutes avec M. Ibrahim pour discuter de vos objectifs, votre niveau actuel et le bon programme pour vous.",
    "home.how.step2.title": "Obtenez votre feuille de route personnalisée",
    "home.how.step2.desc": "Recevez un plan semaine par semaine avec des jalons clairs et des résultats mesurables.",
    "home.how.step3.title": "Atteignez votre objectif",
    "home.how.step3.desc": "Suivez le programme, suivez vos progrès et atteignez votre cible — garanti.",
    "home.how.cta": "Réservez votre appel stratégique gratuit",

    "home.courses.title": "Toutes nos offres de cours",
    "home.courses.subtitle": "Que vous soyez étudiant, professionnel ou apprenant tout au long de la vie, nous avons un programme pour vous.",
    "home.courses.general.title": "Anglais général",
    "home.courses.general.desc": "Construisez une base solide en expression orale, écoute, lecture et écriture.",
    "home.courses.business.title": "Anglais des affaires",
    "home.courses.business.desc": "Maîtrisez la communication professionnelle pour les réunions, e-mails et présentations.",
    "home.courses.ielts.title": "Préparation IELTS & TOEFL",
    "home.courses.ielts.desc": "Atteignez votre score cible avec des stratégies d'examen ciblées et de la pratique.",
    "home.courses.conversation.title": "Pratique de conversation",
    "home.courses.conversation.desc": "Améliorez votre fluidité et votre confiance à travers des conversations naturelles et engageantes.",
    "home.courses.learnMore": "En savoir plus",

    "home.article.badge": "Article à la une",
    "home.article.title": "Dernières nouvelles de Fluentry",
    "home.article.h3": "Le Passeport Non-Dit : Pourquoi l'Anglais Façonne Encore le Monde",
    "home.article.desc": "Explorez comment l'anglais connecte les cultures, les carrières et les opportunités à notre ère mondiale. Une réflexion sur l'importance durable de l'anglais dans le monde moderne.",
    "home.article.by": "Par M. Ibrahim K.",
    "home.article.read": "5 min de lecture",
    "home.article.readArticle": "Lire l'article",

    "home.blog.badge": "Blog d'apprentissage de l'anglais",
    "home.blog.title": "Conseils et stratégies d'experts",
    "home.blog.subtitle": "Apprenez du coach certifié TESOL M. Ibrahim K. Des conseils pratiques pour maîtriser l'anglais plus rapidement.",
    "home.blog.viewAll": "Voir tous les articles",
    "home.blog.readMore": "Lire la suite",

    "home.cta.title": "Prêt à arrêter de lutter et à commencer à réussir ?",
    "home.cta.subtitle": "Réservez un appel stratégique gratuit de 10 minutes. Sans engagement, sans pression — juste un plan clair pour atteindre vos objectifs en anglais.",
    "home.cta.guarantee": "Résultats garantis — ou nous vous coachons gratuitement",
    "home.cta.button": "Réservez votre appel stratégique gratuit",
    "home.cta.viewPrograms": "Voir tous les programmes",
    "home.cta.note": "Appel gratuit 10 min · Sans engagement · En anglais ou en darija",

    // ── About ──
    "about.hero.badge": "Certifié TESOL · Basé au Maroc",
    "about.hero.title": "Rencontrez M. Ibrahim K.",
    "about.hero.subtitle": "Le coach d'anglais axé sur les résultats au Maroc — aidant étudiants et professionnels à obtenir des résultats réels et mesurables depuis 2022.",
    "about.hero.cta1": "Appel stratégique gratuit",
    "about.hero.cta2": "Test de niveau gratuit",
    "about.hero.role": "Coach d'anglais certifié TESOL",
    "about.hero.location": "Tanger, Maroc 🇲🇦",
    "about.guarantee": "Résultats garantis sur tous les programmes signature — si vous n'atteignez pas votre objectif, M. Ibrahim vous coache gratuitement jusqu'à ce que vous y arriviez.",
    "about.story.title": "L'histoire derrière Fluentry",
    "about.story.quote": "\"La fluidité vient de la confiance, pas de la perfection. Mon objectif est de rendre l'apprentissage de l'anglais pratique, agréable et personnel pour chaque étudiant.\"",
    "about.story.quoteBy": "— M. Ibrahim K.",
    "about.story.p1": "M. Ibrahim K. est un coach en langue anglaise certifié TESOL avec un baccalauréat en études anglaises et plus de trois ans d'expérience dans l'enseignement au Maroc et à l'international.",
    "about.story.p2": "Il enseigne actuellement l'anglais dans une école privée au Maroc tout en dirigeant Fluentry — sa pratique de coaching en ligne dédiée à aider les étudiants et professionnels motivés à atteindre des objectifs anglais spécifiques et mesurables.",
    "about.story.p3": "Ce qui distingue M. Ibrahim, c'est sa compréhension approfondie des défis uniques auxquels font face les apprenants marocains — l'interférence du français et du darija, la difficulté des sons anglais inexistants en arabe, et la barrière de confiance.",
    "about.story.p4": "Fluentry a été construit sur une croyance simple : les étudiants méritent de payer pour des résultats, pas seulement des heures. Chaque programme est structuré autour d'un résultat clair — soutenu par une garantie de résultats.",
    "about.credentials.title": "Qualifications professionnelles",
    "about.method.badge": "Méthodologie propriétaire",
    "about.method.title": "La méthode Fluency Bridge™",
    "about.method.subtitle": "Une approche axée sur la conversation et la confiance qui comble le fossé entre connaître l'anglais et l'utiliser naturellement — développée spécifiquement pour les apprenants marocains.",
    "about.who.title": "Qui M. Ibrahim enseigne",
    "about.who.subtitle": "Étudiants, professionnels et apprenants tout au long de la vie de tout le Maroc — en ligne et à Tanger.",
    "about.testimonials.title": "Ce que disent les étudiants",
    "about.mission.title": "Notre mission",
    "about.mission.text": "Fournir un coaching anglais en ligne accessible, de haute qualité et personnalisé au Maroc qui transforme les apprenants en communicateurs confiants et naturels — prêts à s'épanouir dans un environnement mondial. Chaque étudiant mérite de payer pour des résultats, pas seulement des heures.",
    "about.cta.title": "Prêt à travailler avec M. Ibrahim ?",
    "about.cta.subtitle": "Réservez un appel stratégique gratuit de 10 minutes. Sans engagement, sans pression — juste un plan clair pour atteindre vos objectifs en anglais.",
    "about.cta.button": "Appel stratégique gratuit",
    "about.cta.viewPricing": "Voir les programmes et tarifs",
    "about.cta.guarantee": "Résultats garantis sur tous les programmes signature",

    // ── Courses ──
    "courses.title": "Nos programmes d'anglais",
    "courses.subtitle": "Des programmes personnalisés conçus pour les apprenants marocains — des débutants aux professionnels avancés.",
    "courses.hero.badge": "Résultats garantis sur tous les programmes signature",
    "courses.hero.title": "Programmes construits autour de votre objectif",
    "courses.hero.subtitle": "Chaque programme Fluentry est structuré autour d'un résultat spécifique et mesurable. Vous savez exactement ce que vous allez accomplir — et nous le garantissons.",
    "courses.stats.ielts": "Amélioration IELTS moyenne",
    "courses.stats.achieve": "Étudiants atteignant leur objectif",
    "courses.stats.time": "Délai moyen pour les résultats",
    "courses.stats.satisfaction": "Satisfaction garantie",
    "courses.choose.title": "Choisissez votre programme",
    "courses.choose.subtitle": "Pas sûr du programme qui vous convient ? Passez le test de niveau gratuit ou réservez un appel stratégique gratuit de 10 minutes — M. Ibrahim recommandera le meilleur choix.",
    "courses.ielts.title": "Préparation IELTS & TOEFL",
    "courses.ielts.desc": "Atteignez votre score cible — garanti",
    "courses.business.title": "Maîtrise de l'anglais des affaires",
    "courses.business.desc": "Dirigez des réunions, rédigez des e-mails, présentez avec autorité",
    "courses.conversation.title": "Conversation & Fluidité",
    "courses.conversation.desc": "Arrêtez de bloquer — commencez à parler naturellement",
    "courses.general.title": "Anglais général",
    "courses.general.desc": "Construisez une base solide depuis le début",
    "courses.forWho": "POUR QUI",
    "courses.achieve": "CE QUE VOUS ACCOMPLIREZ",
    "courses.bookCall": "Appel stratégique gratuit",
    "courses.startCoaching": "Commencer le coaching",
    "courses.program": "Programme",
    "courses.investment": "Investissement",
    "courses.cta.title": "Pas sûr du programme qui vous convient ?",
    "courses.cta.subtitle": "Réservez un appel stratégique gratuit de 10 minutes. M. Ibrahim évaluera votre niveau, comprendra vos objectifs et recommandera le meilleur programme.",
    "courses.cta.button": "Appel stratégique gratuit sur WhatsApp",
    "courses.cta.note": "Appel gratuit 10 min · Sans engagement · Recommandation personnalisée",

    // ── Pricing ──
    "pricing.title": "Choisissez votre forfait",
    "pricing.subtitle": "Tarifs transparents. Aucun frais caché. Annulez à tout moment.",
    "pricing.perHour": "par heure",
    "pricing.perMonth": "par mois",
    "pricing.mostPopular": "Le plus populaire",
    "pricing.bestValue": "Meilleur rapport qualité-prix",
    "pricing.getStarted": "Commencer",
    "pricing.bookCall": "Appel stratégique gratuit",
    "pricing.freeConsult": "Consultation gratuite 10 min · Sans engagement",
    "pricing.saveVsStandard": "Économie vs Standard",
    "pricing.standard": "Standard",
    "pricing.intensive": "Intensif",
    "pricing.accelerator": "Accélérateur",
    "pricing.hero.urgency": "Seulement 3 places disponibles ce mois — les prix pourraient augmenter en avril",
    "pricing.hero.h1a": "Plus vous pratiquez,",
    "pricing.hero.h1b": "Moins vous payez par heure.",
    "pricing.hero.desc": "Contrairement aux écoles de langues qui facturent un tarif fixe, Fluentry récompense les étudiants sérieux. Réservez plus de séances — payez moins par heure — progressez plus vite.",
    "pricing.hero.studentsCoached": "100+ Étudiants coachés",
    "pricing.hero.rating": "Note moyenne 4,9★",
    "pricing.hero.results": "Résultats en 8 semaines",
    "pricing.hero.guarantee": "Résultats garantis",
    "pricing.plans.badge": "Choisissez votre rythme",
    "pricing.plans.title": "Tous les forfaits — 1-on-1 avec M. Ibrahim",
    "pricing.plans.subtitle": "Chaque forfait comprend des séances privées, un plan d'étude personnalisé et le support WhatsApp. Plus vous réservez de séances, plus votre tarif horaire est bas — et plus vite vous atteignez la fluidité.",

    // ── Pricing (extended) ──
    "pricing.hero.subtitle": "Contrairement aux écoles de langues qui facturent un tarif fixe, Fluentry récompense les étudiants sérieux. Réservez plus de séances — payez moins par heure — progressez plus vite.",
    "pricing.trust.students": "100+ Étudiants coachtés",
    "pricing.trust.rating": "Note moyenne 4,9★",
    "pricing.trust.results": "Résultats en 8 semaines",
    "pricing.trust.guarantee": "Résultats garantis",
    "pricing.plan.standard": "Standard",
    "pricing.plan.intensive": "Intensif",
    "pricing.plan.accelerator": "Accélérateur",
    "pricing.plans.eyebrow": "Choisissez votre rythme",
    "pricing.ratePerSession": "Tarif par séance",
    "pricing.standard.sessions": "8 séances/mois · 2 par semaine",
    "pricing.standard.f1": "2 × séances privées d'1 heure/semaine",
    "pricing.standard.f2": "Plan de cours personnalisé",
    "pricing.standard.f3": "Support WhatsApp",
    "pricing.standard.f4": "Feedback expression orale & compréhension",
    "pricing.standard.f5": "Bilan mensuel de progression",
    "pricing.standard.nudge": "💡 Passez à Intensif et économisez 80 MAD/mois",
    "pricing.noCommit": "Appel gratuit 10 min d'abord · Sans engagement",
    "pricing.intensive.badge": "⭐ LE PLUS POPULAIRE — MEILLEUR RAPPORT",
    "pricing.intensive.sessions": "16 séances/mois · 4 par semaine",
    "pricing.intensive.savings": "Vous économisez 80 MAD/mois vs tarif Standard pour 16 séances",
    "pricing.intensive.f1": "4 × séances privées d'1 heure/semaine",
    "pricing.intensive.f2": "Plan de cours personnalisé",
    "pricing.intensive.f3": "Support WhatsApp",
    "pricing.intensive.f4": "Feedback sur les 4 compétences",
    "pricing.intensive.f5": "Plan d'étude IELTS (si applicable)",
    "pricing.intensive.f6": "Coaching e-mail & présentation",
    "pricing.intensive.f7": "Bilan bimensuel de progression",
    "pricing.intensive.social": "🔥 7 étudiants sur 10 choisissent ce forfait",
    "pricing.intensive.cta": "Commencer — Meilleur rapport",
    "pricing.accelerator.badge": "⚡ RÉSULTATS LES PLUS RAPIDES",
    "pricing.accelerator.sessions": "24 séances/mois · 6 par semaine",
    "pricing.accelerator.savings": "Vous économisez 360 MAD/mois vs tarif Standard pour 24 séances",
    "pricing.accelerator.f1": "6 × séances privées d'1 heure/semaine",
    "pricing.accelerator.f2": "Plan de cours personnalisé",
    "pricing.accelerator.f3": "Support WhatsApp",
    "pricing.accelerator.f4": "Feedback sur les 4 compétences",
    "pricing.accelerator.f5": "Plan d'étude IELTS personnalisé",
    "pricing.accelerator.f6": "Programme de communication professionnelle",
    "pricing.accelerator.f7": "Anglais des réunions et négociations",
    "pricing.accelerator.f8": "Planification prioritaire",
    "pricing.accelerator.f9": "Bilan hebdomadaire de progression",
    "pricing.accelerator.scarcity": "⚠️ Seulement 2 places Accélérateur disponibles ce mois",
    "pricing.accelerator.cta": "Réserver ma place",
    "pricing.payPerLesson.title": "Paiement par cours",
    "pricing.payPerLesson.desc": "Sans engagement · 80 MAD/séance",
    "pricing.bookNow": "Réserver",
    "pricing.group.title": "Étude en groupe",
    "pricing.group.desc": "200 MAD/mois · 30 MAD/séance",
    "pricing.group.cta": "Rejoindre le groupe",
    "pricing.compare.title": "Comment Fluentry se compare aux autres options",
    "pricing.compare.option": "Option",
    "pricing.compare.costHr": "Coût/h",
    "pricing.compare.oneOnOne": "1-à-1?",
    "pricing.compare.personalised": "Personnalisé?",
    "pricing.compare.school": "École de langues (Maroc)",
    "pricing.compare.preply": "Tuteur Preply / iTalki",
    "pricing.compare.apps": "Duolingo / Applications",
    "pricing.compare.fluentry": "Fluentry (Intensif)",
    "pricing.compare.note": "Coaching privé et personnalisé à une fraction du coût des écoles de langues.",
    "pricing.programs.eyebrow": "Axé sur les objectifs",
    "pricing.programs.title": "Programmes structurés",
    "pricing.programs.subtitle": "Vous avez un objectif précis — un score IELTS ou la fluidité professionnelle? Ces programmes à durée fixe incluent une feuille de route claire et une garantie de résultats.",
    "pricing.ielts.eyebrow": "Préparation IELTS",
    "pricing.ielts.title": "Programme IELTS 8 semaines",
    "pricing.ielts.sessions": "2 séances/semaine · 16 séances au total",
    "pricing.ielts.desc": "16 séances privées sur 8 semaines, entièrement axées sur l'IELTS. Les quatre sections couvertes avec tests pratiques et feedback détaillé chaque semaine.",
    "pricing.ielts.f1": "16 × séances privées d'1 heure",
    "pricing.ielts.f2": "Les 4 sections IELTS: L, R, W, S",
    "pricing.ielts.f3": "Plan d'étude IELTS personnalisé",
    "pricing.ielts.f4": "Tests blancs avec feedback de score",
    "pricing.ielts.f5": "Support WhatsApp tout au long",
    "pricing.ielts.f6": "Garantie de résultats incluse",
    "pricing.business.eyebrow": "Anglais des affaires",
    "pricing.business.title": "Anglais des affaires 12 semaines",
    "pricing.business.sessions": "2 séances/semaine · 24 séances au total",
    "pricing.business.desc": "24 séances privées sur 12 semaines, axées sur l'anglais professionnel. Maîtrisez les e-mails, réunions, présentations et le vocabulaire professionnel.",
    "pricing.business.f1": "24 × séances privées d'1 heure",
    "pricing.business.f2": "Programme de communication professionnelle",
    "pricing.business.f3": "Rédaction d'e-mails professionnels",
    "pricing.business.f4": "Anglais des réunions et négociations",
    "pricing.business.f5": "Coaching de présentation",
    "pricing.business.f6": "Support WhatsApp tout au long",
    "pricing.included.title": "Ce que comprend chaque séance",
    "pricing.included.goal.title": "Pratique axée sur les objectifs",
    "pricing.included.goal.desc": "Chaque séance est construite autour de votre objectif spécifique — IELTS, affaires ou fluidité.",
    "pricing.included.feedback.title": "Feedback en temps réel",
    "pricing.included.feedback.desc": "Corrections instantanées sur la prononciation, la grammaire et le vocabulaire pendant que vous parlez.",
    "pricing.included.whatsapp.title": "Support WhatsApp",
    "pricing.included.whatsapp.desc": "Posez des questions et obtenez des retours entre les séances, à tout moment.",
    "pricing.included.progress.title": "Suivi de progression",
    "pricing.included.progress.desc": "Rapports mensuels montrant exactement vos progrès et les prochaines étapes.",
    "pricing.testimonials.title": "Ce que disent les étudiants",
    "pricing.faq.title": "Questions fréquentes",
    "pricing.cta.guarantee": "Résultats garantis — ou nous vous coachons gratuitement",
    "pricing.cta.title": "Pas sûr du forfait qui vous convient?",
    "pricing.cta.subtitle": "Réservez un appel gratuit de 10 minutes avec M. Ibrahim. Il écoutera vos objectifs et recommandera le forfait exact adapté à votre emploi du temps et budget.",
    "pricing.cta.urgency": "⏳ Seulement 3 places disponibles ce mois — les prix pourraient augmenter en avril",
    "pricing.cta.button": "Appel stratégique gratuit",
    "pricing.cta.freeTest": "Passer d'abord le test de niveau gratuit",

    // ── Courses (extended) ──
    "courses.grid.title": "Choisissez votre programme",
    "courses.grid.subtitle": "Pas sûr du programme qui vous convient? Passez le test de niveau gratuit ou réservez un appel stratégique gratuit de 10 minutes.",
    "courses.card.whoFor": "Pour qui",
    "courses.card.achieve": "Ce que vous accomplirez",
    "courses.card.program": "Programme",
    "courses.sessions.title": "Ce que comprend chaque séance",
    "courses.sessions.focus.title": "Focus personnalisé",
    "courses.sessions.focus.desc": "Chaque séance est construite autour de vos objectifs spécifiques, votre niveau et les défis que vous rencontrez en tant qu'apprenant marocain.",
    "courses.sessions.progress.title": "Suivi de progression",
    "courses.sessions.progress.desc": "Des jalons clairs et des bilans réguliers pour que vous sachiez toujours exactement où vous en êtes.",
    "courses.sessions.schedule.title": "Planning flexible",
    "courses.sessions.schedule.desc": "Séances via Google Meet. Reportez jusqu'à 24 heures à l'avance. Votre temps, votre rythme.",
    "courses.testimonials.title": "Résultats des étudiants",
    "courses.cta.freeTest": "Passer le test de niveau gratuit",
    "courses.cta.bookCall": "Appel stratégique gratuit",

    // ── Free Test ──
    "freeTest.title": "Test de niveau d'anglais gratuit",
    "freeTest.subtitle": "Découvrez votre niveau d'anglais exact en 10 minutes. Obtenez un rapport personnalisé avec des recommandations.",
    "freeTest.start": "Commencer le test gratuit",

    // ── Success Stories ──
    "success.title": "Témoignages d'étudiants",
    "success.subtitle": "De vrais résultats de vrais étudiants marocains qui ont transformé leur anglais.",

    // ── Free Resources ──
    "resources.title": "Ressources anglais gratuites",
    "resources.subtitle": "Exercices, guides et outils pour améliorer votre anglais — totalement gratuits.",

    // ── Common ──
    "common.learnMore": "En savoir plus",
    "common.bookCall": "Appel stratégique gratuit",
    "common.freeCall": "Appel gratuit 10 min · Sans engagement",
    "common.whatsapp": "WhatsApp",
    "common.readMore": "Lire la suite",
    "common.viewAll": "Voir tout",
    "common.download": "Télécharger gratuitement",
    "common.startNow": "Commencer maintenant",
    "common.perMonth": "/mois",
    "common.perHour": "/heure",
    "common.save": "Économie",

    // ── Testimonials ──
    "testimonials.title": "Des apprenants de tout le Maroc nous font confiance",
    "testimonials.subtitle": "Des histoires vraies et des résultats réels d'étudiants qui ont transformé leur anglais avec Fluentry.",
    "testimonials.1.name": "Fatima Z.",
    "testimonials.1.location": "Étudiante IELTS, Casablanca",
    "testimonials.1.quote": "Le coaching d'Ibrahim a complètement changé ma façon d'aborder l'anglais. Je suis passée de la traduction mot à mot à penser directement en anglais. Mon score IELTS a progressé de 1,5 bandes !",
    "testimonials.2.name": "Youssef B.",
    "testimonials.2.location": "Directeur marketing, Rabat",
    "testimonials.2.quote": "En tant que professionnel, j'avais besoin d'améliorer rapidement mes compétences de présentation. Le cours d'anglais des affaires d'Ibrahim m'a donné la confiance pour diriger des réunions internationales.",
    "testimonials.3.name": "Amina K.",
    "testimonials.3.location": "Étudiante universitaire, Tanger",
    "testimonials.3.quote": "Les ressources gratuites sont incroyables ! Le guide des expressions idiomatiques et les exercices d'écoute m'ont tellement aidée. C'est le meilleur endroit pour apprendre l'anglais au Maroc.",
    "testimonials.4.name": "Mehdi L.",
    "testimonials.4.location": "Développeur logiciel, Marrakech",
    "testimonials.4.quote": "J'étais bloqué à un niveau intermédiaire depuis des années. Les séances personnalisées en tête-à-tête m'ont aidé à franchir ce cap. Je peux enfin exprimer des idées complexes clairement.",
    "testimonials.5.name": "Salma C.",
    "testimonials.5.location": "Étudiante TOEFL, Fès",
    "testimonials.5.quote": "La pratique de l'expression orale était inestimable. M. Ibrahim est patient et sait exactement comment corriger la prononciation des locuteurs arabes. J'ai obtenu 28/30 à la section expression orale du TOEFL !",

    // ── Newsletter ──
    "newsletter.title": "Recevez des conseils d'anglais chaque semaine",
    "newsletter.subtitle": "Rejoignez des centaines d'étudiants qui reçoivent gratuitement des conseils d'apprentissage, des explications de grammaire et des stratégies d'étude chaque semaine.",
    "newsletter.placeholder": "Entrez votre e-mail",
    "newsletter.button": "S'abonner gratuitement",
    "newsletter.subscribing": "Inscription...",
    "newsletter.disclaimer": "Pas de spam. Désabonnement à tout moment. 100% gratuit pour toujours.",
    "newsletter.error": "Veuillez entrer une adresse e-mail valide",
    "newsletter.success": "Merci pour votre inscription ! Vérifiez votre e-mail pour confirmation.",

    // ── Blog posts (Home) ──
    "home.blog.post1.title": "Cours d'anglais en ligne pour les Marocains",
    "home.blog.post1.excerpt": "Comparez les prix et les méthodes pour trouver la meilleure façon d'apprendre l'anglais en ligne.",
    "home.blog.post1.category": "Guide d'apprentissage",
    "home.blog.post1.readTime": "12 min",
    "home.blog.post2.title": "De A2 à B1 en 6 mois",
    "home.blog.post2.excerpt": "Un plan pratique de 6 mois avec un programme hebdomadaire pour améliorer votre anglais.",
    "home.blog.post2.category": "Plan d'apprentissage",
    "home.blog.post2.readTime": "10 min",
    "home.blog.post3.title": "15 meilleures applications pour apprendre l'anglais",
    "home.blog.post3.excerpt": "Découvrez les meilleurs outils numériques pour le vocabulaire, l'écoute et la lecture.",
    "home.blog.post3.category": "Revue d'outils",
    "home.blog.post3.readTime": "14 min",
    "home.blog.post4.title": "5 défis des apprenants marocains",
    "home.blog.post4.excerpt": "Comprenez les obstacles uniques et les solutions pratiques pour les apprenants marocains.",
    "home.blog.post4.category": "Insights d'apprentissage",
    "home.blog.post4.readTime": "11 min",
  },

  ar: {
    // ── Navbar ──
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.courses": "الدورات",
    "nav.groupCoaching": "التدريب الجماعي",
    "nav.pricing": "الأسعار",
    "nav.freeTest": "اختبار مجاني",
    "nav.successStories": "قصص النجاح",
    "nav.freeResources": "موارد مجانية",
    "nav.bookLesson": "احجز درساً",
    "nav.language": "العربية",

    // ── Footer ──
    "footer.tagline": "طريقك نحو إتقان اللغة الإنجليزية — تدريب شخصي للمهنيين والطلاب المغاربة.",
    "footer.quickLinks": "روابط سريعة",
    "footer.programs": "البرامج",
    "footer.getInTouch": "تواصل معنا",
    "footer.ielts": "تحضير IELTS",
    "footer.business": "الإنجليزية للأعمال",
    "footer.group": "التدريب الجماعي",
    "footer.conversation": "ممارسة المحادثة",
    "footer.general": "الإنجليزية العامة",
    "footer.freeResources": "موارد مجانية",
    "footer.pronunciationAudit": "تدقيق النطق المجاني",
    "footer.rights": "جميع الحقوق محفوظة. مقرنا في طنجة، المغرب.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.bookCall": "احجز مكالمة استراتيجية مجانية",
    "footer.home": "الرئيسية",
    "footer.about": "عن الأستاذ إبراهيم",
    "footer.courses": "الدورات",
    "footer.pricing": "الأسعار",
    "footer.freeTest": "اختبار المستوى المجاني",
    "footer.blog": "المدونة",
    "footer.successStories": "قصص النجاح",

    // ── Home ──
    "home.hero.badge": "🇲🇦 المدرب الأول للغة الإنجليزية في المغرب",
    "home.hero.title": "تحدث الإنجليزية بثقة — النتائج مضمونة",
    "home.hero.subtitle": "تدريب شخصي فردي على اللغة الإنجليزية للمهنيين والطلاب المغاربة. IELTS، الإنجليزية للأعمال، الطلاقة في المحادثة — نتائج حقيقية في 8 أسابيع.",
    "home.hero.cta1": "احجز مكالمة استراتيجية مجانية",
    "home.hero.cta2": "عرض البرامج والأسعار",
    "home.hero.students": "أكثر من 100 طالب",
    "home.hero.rating": "تقييم 4.9★",
    "home.hero.weeks": "نتائج في 8 أسابيع",
    "home.hero.guarantee": "ضمان النتائج",
    "home.hero.badge2": "مدرب معتمد TESOL · مقيم في المغرب",
    "home.hero.h1a": "من التردد إلى الطلاقة.",
    "home.hero.h1b": "حقق 7.5+ في IELTS",
    "home.hero.h1c": "في 8 أسابيع.",
    "home.hero.bilingual": "تتعثر في التحدث بالإنجليزية بطلاقة؟",
    "home.hero.desc": "مدرب الإنجليزية الأكثر تركيزاً على النتائج في المغرب. الأستاذ إبراهيم ك. يقدم نتائج حقيقية — لا مجرد دروس.",
    "home.hero.desc2": "90% من الطلاب يحققون هدفهم في 8 أسابيع.",
    "home.hero.guarantee2": "النتائج مضمونة — أو ندربك مجاناً حتى تنجح",
    "home.hero.noCommit": "بدون التزام · استشارة مجانية 10 دقائق · نتائج مضمونة",
    "home.hero.studentsCoached": "طالب تم تدريبه",
    "home.hero.reachGoal": "يحققون هدفهم",
    "home.hero.avgRating": "متوسط التقييم",
    "home.hero.yearsExp": "سنوات خبرة",

    "home.results.ieltsBands": "متوسط تحسن IELTS",
    "home.results.achieve": "الطلاب يحققون درجتهم المستهدفة",
    "home.results.time": "متوسط الوقت للحصول على النتائج",
    "home.results.satisfaction": "رضا الطلاب",

    "home.intro.title": "توقف عن شراء الدروس. ابدأ بشراء النتائج.",
    "home.intro.desc": "معظم مدرسي الإنجليزية يبيعونك ساعات. Fluentry يبيعك نتائج. يعمل الأستاذ إبراهيم ك. مع مجموعة مختارة من الطلاب المتحمسين في المغرب لتقديم شيء واحد:",
    "home.intro.strong": "تقدم قابل للقياس ومضمون",
    "home.intro.desc2": "— سواء كان ذلك درجة IELTS أو ترقية وظيفية أو الثقة لقيادة الاجتماعات بالإنجليزية.",
    "home.intro.quote": "\"الإنجليزية ليست مجرد قواعد ومفردات. إنها ثقة ووضوح وتواصل — وأضمن لك أنك ستشعر بالثلاثة.\"",
    "home.intro.quoteAuthor": "— الأستاذ إبراهيم ك.، مدرب معتمد TESOL ومؤسس Fluentry",

    "home.programs.title": "برامج قائمة على النتائج",
    "home.programs.subtitle": "ليست مجرد دروس — برامج تحول كاملة بأهداف واضحة ومعالم منظمة وضمان نتائج.",
    "home.programs.ielts.badge": "الأكثر شعبية",
    "home.programs.ielts.title": "مسرّع IELTS لـ 8 أسابيع",
    "home.programs.ielts.for": "للطلاب الراغبين في الدراسة في الخارج",
    "home.programs.ielts.desc": "حقق 7.5+ في 8 أسابيع بمنهجيتنا المثبتة. خطة دراسية مخصصة واختبارات أسبوعية وتغذية راجعة مباشرة على جميع المهارات الأربع.",
    "home.programs.ielts.price": "12,000 درهم",
    "home.programs.ielts.priceNote": "برنامج كامل 8 أسابيع · نتائج مضمونة",
    "home.programs.ielts.guarantee": "ضمان استرداد المال إذا لم تحقق هدفك",
    "home.programs.business.badge": "دخل مرتفع",
    "home.programs.business.title": "إتقان الإنجليزية للأعمال 12 أسبوعاً",
    "home.programs.business.for": "للمهنيين في الدار البيضاء والرباط",
    "home.programs.business.desc": "قُد الاجتماعات الدولية واكتب رسائل بريد إلكتروني مقنعة وقدّم بثقة. مصمم للمهنيين في المالية والتقنية والإدارة.",
    "home.programs.business.price": "15,000 درهم",
    "home.programs.business.priceNote": "برنامج كامل 12 أسبوعاً · نتائج مضمونة",
    "home.programs.business.guarantee": "طلاقة مهنية مضمونة",
    "home.programs.vip.badge": "VIP نخبة",
    "home.programs.vip.title": "تدريب VIP كونسيرج",
    "home.programs.vip.for": "للمديرين التنفيذيين والمستثمرين الجادين",
    "home.programs.vip.desc": "جلسات فردية غير محدودة، وصول واتساب 24/7، منهج مخصص بالكامل، ومشاركة مباشرة في كل جانب من رحلتك.",
    "home.programs.vip.price": "25,000 درهم",
    "home.programs.vip.priceNote": "برنامج VIP كامل · وصول غير محدود",
    "home.programs.vip.guarantee": "ضمان نتائج كامل — بدون استثناءات",
    "home.programs.vip.cta": "التقدم لبرنامج VIP",
    "home.programs.flexible": "تفضل خطة شهرية مرنة؟",
    "home.programs.viewPricing": "عرض جميع خيارات الأسعار →",
    "home.programs.bookCall": "احجز مكالمة استراتيجية مجانية",

    "home.why.title": "لماذا Fluentry مختلف",
    "home.why.subtitle": "هناك مئات من مدرسي الإنجليزية في المغرب. إليك لماذا يختار المتعلمون الجادون Fluentry.",
    "home.why.method.title": "طريقة Fluency Bridge™",
    "home.why.method.desc": "نهجنا الخاص القائم على المحادثة أولاً وبناء الثقة. لا نعلم قواعد النحو — نبني مهارات تواصل حقيقية تنتقل إلى الحياة الواقعية.",
    "home.why.guarantee.title": "ضمان النتائج",
    "home.why.guarantee.desc": "إذا لم تحقق درجة IELTS المستهدفة أو هدف الطلاقة خلال مدة البرنامج، نواصل تدريبك مجاناً حتى تحققه. صفر مخاطر.",
    "home.why.morocco.title": "خبرة خاصة بالمغرب",
    "home.why.morocco.desc": "يفهم الأستاذ إبراهيم ك. التحديات الدقيقة التي يواجهها المتعلمون المغاربة — من تدخل الفرنسية إلى أنماط النطق العربية — ويعالجها مباشرة.",
    "home.why.table.feature": "الميزة",
    "home.why.table.fluentry": "Fluentry",
    "home.why.table.typical": "مدرس عادي",
    "home.why.table.outcome": "برامج قائمة على النتائج",
    "home.why.table.outcomeF": "✅ نعم",
    "home.why.table.outcomeT": "❌ دروس بالساعة",
    "home.why.table.resultsG": "ضمان النتائج",
    "home.why.table.resultsFY": "✅ نعم",
    "home.why.table.resultsTN": "❌ لا",
    "home.why.table.moroccan": "منهج خاص بالمغرب",
    "home.why.table.moroccanF": "✅ نعم",
    "home.why.table.moroccanT": "❌ عام",
    "home.why.table.tesol": "مدرب معتمد TESOL",
    "home.why.table.tesolF": "✅ نعم",
    "home.why.table.tesolT": "⚠️ غالباً لا",
    "home.why.table.tracking": "تتبع منظم للتقدم",
    "home.why.table.trackingF": "✅ نعم",
    "home.why.table.trackingT": "❌ لا",
    "home.why.table.method": "طريقة Fluency Bridge™",
    "home.why.table.methodF": "✅ حصري",
    "home.why.table.methodT": "❌ لا",

    "home.how.title": "كيف يعمل",
    "home.how.step1.title": "احجز مكالمة استراتيجية مجانية",
    "home.how.step1.desc": "10 دقائق مع الأستاذ إبراهيم لمناقشة أهدافك ومستواك الحالي والبرنامج المناسب لك.",
    "home.how.step2.title": "احصل على خارطة طريق مخصصة",
    "home.how.step2.desc": "احصل على خطة أسبوعية بمعالم واضحة ونتائج قابلة للقياس.",
    "home.how.step3.title": "حقق هدفك",
    "home.how.step3.desc": "اتبع البرنامج وتتبع تقدمك وابلغ هدفك — مضمون.",
    "home.how.cta": "احجز مكالمتك الاستراتيجية المجانية",

    "home.courses.title": "جميع عروض الدورات",
    "home.courses.subtitle": "سواء كنت طالباً أو مهنياً أو متعلماً مدى الحياة، لدينا برنامج مناسب لك.",
    "home.courses.general.title": "الإنجليزية العامة",
    "home.courses.general.desc": "ابنِ أساساً قوياً في التحدث والاستماع والقراءة والكتابة.",
    "home.courses.business.title": "الإنجليزية للأعمال",
    "home.courses.business.desc": "أتقن التواصل المهني للاجتماعات والرسائل والعروض التقديمية.",
    "home.courses.ielts.title": "تحضير IELTS و TOEFL",
    "home.courses.ielts.desc": "حقق درجتك المستهدفة باستراتيجيات اختبار مركزة وممارسة.",
    "home.courses.conversation.title": "ممارسة المحادثة",
    "home.courses.conversation.desc": "حسّن طلاقتك وثقتك من خلال محادثات طبيعية وجذابة.",
    "home.courses.learnMore": "اعرف المزيد",

    "home.article.badge": "مقال مميز",
    "home.article.title": "آخر أخبار Fluentry",
    "home.article.h3": "جواز السفر غير المُعلن: لماذا لا تزال الإنجليزية تشكّل العالم",
    "home.article.desc": "استكشف كيف تربط الإنجليزية الثقافات والمهن والفرص في عصرنا العالمي. تأمل مدروس في الأهمية الدائمة للإنجليزية في العالم الحديث.",
    "home.article.by": "بقلم الأستاذ إبراهيم ك.",
    "home.article.read": "5 دقائق قراءة",
    "home.article.readArticle": "اقرأ المقال",

    "home.blog.badge": "مدونة تعلم الإنجليزية",
    "home.blog.title": "نصائح واستراتيجيات الخبراء",
    "home.blog.subtitle": "تعلم من المدرب المعتمد TESOL الأستاذ إبراهيم ك. نصائح عملية لمساعدتك على إتقان الإنجليزية بشكل أسرع.",
    "home.blog.viewAll": "عرض جميع مقالات المدونة",
    "home.blog.readMore": "اقرأ المزيد",

    "home.cta.title": "هل أنت مستعد للتوقف عن المعاناة والبدء في التحقيق؟",
    "home.cta.subtitle": "احجز مكالمة استراتيجية مجانية لمدة 10 دقائق. بدون التزام، بدون ضغط — فقط خطة واضحة للوصول إلى أهدافك في اللغة الإنجليزية.",
    "home.cta.guarantee": "النتائج مضمونة — أو ندربك مجاناً",
    "home.cta.button": "احجز مكالمتك الاستراتيجية المجانية",
    "home.cta.viewPrograms": "عرض جميع البرامج",
    "home.cta.note": "مكالمة مجانية 10 دقائق · بدون التزام · بالإنجليزية أو الدارجة",

    // ── About ──
    "about.hero.badge": "معتمد TESOL · مقيم في المغرب",
    "about.hero.title": "تعرف على الأستاذ إبراهيم ك.",
    "about.hero.subtitle": "مدرب الإنجليزية الأكثر تركيزاً على النتائج في المغرب — يساعد الطلاب والمهنيين على تحقيق نتائج حقيقية وقابلة للقياس منذ 2022.",
    "about.hero.cta1": "احجز مكالمة استراتيجية مجانية",
    "about.hero.cta2": "اجري اختبار المستوى المجاني",
    "about.hero.role": "مدرب لغة إنجليزية معتمد TESOL",
    "about.hero.location": "طنجة، المغرب 🇲🇦",
    "about.guarantee": "النتائج مضمونة على جميع البرامج الأساسية — إذا لم تحقق هدفك، يدربك الأستاذ إبراهيم مجاناً حتى تحققه.",
    "about.story.title": "القصة وراء Fluentry",
    "about.story.quote": "\"الطلاقة تأتي من الثقة، لا من الكمال. هدفي هو جعل تعلم الإنجليزية عملياً وممتعاً وشخصياً لكل طالب.\"",
    "about.story.quoteBy": "— الأستاذ إبراهيم ك.",
    "about.story.p1": "الأستاذ إبراهيم ك. مدرب لغة إنجليزية معتمد TESOL يحمل بكالوريوس في الدراسات الإنجليزية وأكثر من ثلاث سنوات من الخبرة في تدريس المتعلمين في المغرب ودولياً.",
    "about.story.p2": "يدرّس حالياً اللغة الإنجليزية في مدرسة خاصة في المغرب بينما يدير Fluentry — ممارسته التدريبية عبر الإنترنت المخصصة لمساعدة الطلاب والمهنيين المتحمسين على تحقيق أهداف إنجليزية محددة وقابلة للقياس.",
    "about.story.p3": "ما يميز الأستاذ إبراهيم هو فهمه العميق للتحديات الفريدة التي يواجهها المتعلمون المغاربة — تدخل الفرنسية والدارجة، وصعوبة الأصوات الإنجليزية غير الموجودة في العربية، وحاجز الثقة.",
    "about.story.p4": "بُني Fluentry على اعتقاد بسيط: يستحق الطلاب الدفع مقابل النتائج، لا مجرد الساعات. كل برنامج منظم حول نتيجة واضحة — مدعوم بضمان النتائج.",
    "about.credentials.title": "المؤهلات المهنية",
    "about.method.badge": "منهجية خاصة",
    "about.method.title": "طريقة Fluency Bridge™",
    "about.method.subtitle": "نهج يُعطي الأولوية للمحادثة وبناء الثقة يسد الفجوة بين معرفة الإنجليزية واستخدامها بشكل طبيعي — طُوِّر خصيصاً للمتعلمين المغاربة.",
    "about.who.title": "من يدرّس الأستاذ إبراهيم",
    "about.who.subtitle": "طلاب ومهنيون ومتعلمون مدى الحياة من جميع أنحاء المغرب — عبر الإنترنت وفي طنجة.",
    "about.testimonials.title": "ماذا يقول الطلاب",
    "about.mission.title": "رسالتنا",
    "about.mission.text": "تقديم تدريب إنجليزي شخصي عالي الجودة وسهل الوصول عبر الإنترنت في المغرب يحول المتعلمين إلى متواصلين واثقين وطبيعيين — مستعدين للازدهار في بيئة عالمية. كل طالب يستحق الدفع مقابل النتائج، لا مجرد الساعات.",
    "about.cta.title": "هل أنت مستعد للعمل مع الأستاذ إبراهيم؟",
    "about.cta.subtitle": "احجز مكالمة استراتيجية مجانية لمدة 10 دقائق. بدون التزام، بدون ضغط — فقط خطة واضحة للوصول إلى أهدافك في اللغة الإنجليزية.",
    "about.cta.button": "احجز مكالمة استراتيجية مجانية",
    "about.cta.viewPricing": "عرض البرامج والأسعار",
    "about.cta.guarantee": "النتائج مضمونة على جميع البرامج الأساسية",

    // ── Courses ──
    "courses.title": "برامجنا في اللغة الإنجليزية",
    "courses.subtitle": "برامج مخصصة مصممة للمتعلمين المغاربة — من المبتدئين إلى المهنيين المتقدمين.",
    "courses.hero.badge": "النتائج مضمونة على جميع البرامج الأساسية",
    "courses.hero.title": "برامج مبنية حول هدفك",
    "courses.hero.subtitle": "كل برنامج في Fluentry منظم حول نتيجة محددة وقابلة للقياس. تعرف بالضبط ما ستحققه — ونحن نضمنه.",
    "courses.stats.ielts": "متوسط تحسن IELTS",
    "courses.stats.achieve": "الطلاب يحققون هدفهم",
    "courses.stats.time": "متوسط الوقت للحصول على النتائج",
    "courses.stats.satisfaction": "رضا مضمون",
    "courses.choose.title": "اختر برنامجك",
    "courses.choose.subtitle": "غير متأكد من البرنامج المناسب لك؟ اجري اختبار المستوى المجاني أو احجز مكالمة استراتيجية مجانية — سيوصي الأستاذ إبراهيم بالخيار الأفضل.",
    "courses.ielts.title": "تحضير IELTS و TOEFL",
    "courses.ielts.desc": "حقق درجتك المستهدفة — مضمون",
    "courses.business.title": "إتقان الإنجليزية للأعمال",
    "courses.business.desc": "قُد الاجتماعات، اكتب الرسائل، قدّم بثقة",
    "courses.conversation.title": "المحادثة والطلاقة",
    "courses.conversation.desc": "توقف عن التردد — ابدأ الحديث بشكل طبيعي",
    "courses.general.title": "الإنجليزية العامة",
    "courses.general.desc": "ابنِ أساساً قوياً من الصفر",
    "courses.forWho": "لمن هذا البرنامج",
    "courses.achieve": "ما ستحققه",
    "courses.bookCall": "احجز مكالمة استراتيجية مجانية",
    "courses.startCoaching": "ابدأ التدريب",
    "courses.program": "البرنامج",
    "courses.investment": "الاستثمار",
    "courses.cta.title": "غير متأكد من البرنامج المناسب لك؟",
    "courses.cta.subtitle": "احجز مكالمة استراتيجية مجانية لمدة 10 دقائق. سيقيّم الأستاذ إبراهيم مستواك ويفهم أهدافك ويوصي بأفضل برنامج.",
    "courses.cta.button": "احجز مكالمة استراتيجية مجانية على واتساب",
    "courses.cta.note": "مكالمة مجانية 10 دقائق · بدون التزام · توصية شخصية",

    // ── Pricing ──
    "pricing.title": "اختر خطتك",
    "pricing.subtitle": "أسعار شفافة. لا رسوم خفية. إلغاء في أي وقت.",
    "pricing.perHour": "في الساعة",
    "pricing.perMonth": "في الشهر",
    "pricing.mostPopular": "الأكثر شعبية",
    "pricing.bestValue": "أفضل قيمة",
    "pricing.getStarted": "ابدأ الآن",
    "pricing.bookCall": "احجز مكالمة استراتيجية مجانية",
    "pricing.freeConsult": "استشارة مجانية 10 دقائق · بدون التزام",
    "pricing.saveVsStandard": "وفر مقارنة بالخطة العادية",
    "pricing.standard": "عادي",
    "pricing.intensive": "مكثف",
    "pricing.accelerator": "مسرّع",
    "pricing.hero.urgency": "3 أماكن فقط متاحة هذا الشهر — قد ترتفع الأسعار في أبريل",
    "pricing.hero.h1a": "كلما تدربت أكثر،",
    "pricing.hero.h1b": "كلما دفعت أقل في الساعة.",
    "pricing.hero.desc": "على عكس مدارس اللغات التي تفرض سعراً ثابتاً، يكافئ Fluentry الطلاب الجادين. احجز المزيد من الجلسات — ادفع أقل في الساعة — تقدم بشكل أسرع.",
    "pricing.hero.studentsCoached": "أكثر من 100 طالب تم تدريبه",
    "pricing.hero.rating": "متوسط تقييم 4.9★",
    "pricing.hero.results": "نتائج في 8 أسابيع",
    "pricing.hero.guarantee": "نتائج مضمونة",
    "pricing.plans.badge": "اختر وتيرتك",
    "pricing.plans.title": "جميع الخطط — جلسات فردية مع الأستاذ إبراهيم",
    "pricing.plans.subtitle": "تتضمن كل خطة جلسات خاصة وخطة دراسية مخصصة ودعم واتساب. كلما حجزت جلسات أكثر، انخفض سعرك بالساعة — وأسرع وصلت إلى الطلاقة.",

    // ── Pricing (extended) ──
    "pricing.hero.subtitle": "على عكس مدارس اللغات التي تفرض سعراً ثابتاً، يكافئ Fluentry الطلاب الجادين. احجز جلسات أكثر — ادفع أقل في الساعة — تقدم بشكل أسرع.",
    "pricing.trust.students": "أكثر من 100 طالب تم تدريبه",
    "pricing.trust.rating": "متوسط تقييم 4.9★",
    "pricing.trust.results": "نتائج في 8 أسابيع",
    "pricing.trust.guarantee": "نتائج مضمونة",
    "pricing.plan.standard": "عادي",
    "pricing.plan.intensive": "مكثف",
    "pricing.plan.accelerator": "مسرّع",
    "pricing.plans.eyebrow": "اختر وتيرتك",
    "pricing.ratePerSession": "سعر الجلسة",
    "pricing.standard.sessions": "8 جلسات/شهر · 2 في الأسبوع",
    "pricing.standard.f1": "2 × جلسات خاصة لمدة ساعة/أسبوع",
    "pricing.standard.f2": "خطة دروس مخصصة",
    "pricing.standard.f3": "دعم واتساب",
    "pricing.standard.f4": "تغذية راجعة على التحدث والاستماع",
    "pricing.standard.f5": "متابعة شهرية للتقدم",
    "pricing.standard.nudge": "💡 انتقل إلى المكثف ووفّر 80 درهم/شهر",
    "pricing.noCommit": "مكالمة مجانية 10 دقائق أولاً · بدون التزام",
    "pricing.intensive.badge": "⭐ الأكثر شعبية — أفضل قيمة",
    "pricing.intensive.sessions": "16 جلسة/شهر · 4 في الأسبوع",
    "pricing.intensive.savings": "توفّر 80 درهم/شهر مقارنةً بسعر الخطة العادية لـ 16 جلسة",
    "pricing.intensive.f1": "4 × جلسات خاصة لمدة ساعة/أسبوع",
    "pricing.intensive.f2": "خطة دروس مخصصة",
    "pricing.intensive.f3": "دعم واتساب",
    "pricing.intensive.f4": "تغذية راجعة على المهارات الأربع",
    "pricing.intensive.f5": "خطة دراسة IELTS (إن انطبق)",
    "pricing.intensive.f6": "تدريب على البريد الإلكتروني والعروضات",
    "pricing.intensive.f7": "مراجعة تقدم كل أسبوعين",
    "pricing.intensive.social": "🔥 7 من كل 10 طلاب يختارون هذه الخطة",
    "pricing.intensive.cta": "ابدأ — أفضل قيمة",
    "pricing.accelerator.badge": "⚡ أسرع نتائج",
    "pricing.accelerator.sessions": "24 جلسة/شهر · 6 في الأسبوع",
    "pricing.accelerator.savings": "توفّر 360 درهم/شهر مقارنةً بسعر الخطة العادية لـ 24 جلسة",
    "pricing.accelerator.f1": "6 × جلسات خاصة لمدة ساعة/أسبوع",
    "pricing.accelerator.f2": "خطة دروس مخصصة",
    "pricing.accelerator.f3": "دعم واتساب",
    "pricing.accelerator.f4": "تغذية راجعة على المهارات الأربع",
    "pricing.accelerator.f5": "خطة دراسة IELTS مخصصة",
    "pricing.accelerator.f6": "منهج التواصل المهني",
    "pricing.accelerator.f7": "إنجليزية الاجتماعات والتفاوض",
    "pricing.accelerator.f8": "جدولة ذات أولوية",
    "pricing.accelerator.f9": "مراجعة تقدم أسبوعية",
    "pricing.accelerator.scarcity": "⚠️ مكانان فقط متاحان في خطة المسرّع هذا الشهر",
    "pricing.accelerator.cta": "احجز مكاني",
    "pricing.payPerLesson.title": "دفع لكل درس",
    "pricing.payPerLesson.desc": "بدون التزام · 80 درهم/جلسة",
    "pricing.bookNow": "احجز",
    "pricing.group.title": "دراسة جماعية",
    "pricing.group.desc": "200 درهم/شهر · 30 درهم/جلسة",
    "pricing.group.cta": "انضم للمجموعة",
    "pricing.compare.title": "كيف يقارن Fluentry بالخيارات الأخرى",
    "pricing.compare.option": "الخيار",
    "pricing.compare.costHr": "التكلفة/ساعة",
    "pricing.compare.oneOnOne": "فردي;",
    "pricing.compare.personalised": "مخصص;",
    "pricing.compare.school": "مدرسة لغات (المغرب)",
    "pricing.compare.preply": "مدرس Preply / iTalki",
    "pricing.compare.apps": "ديولينجو / تطبيقات",
    "pricing.compare.fluentry": "Fluentry (مكثف)",
    "pricing.compare.note": "تدريب خاص ومخصص بجزء بسيط من تكلفة مدارس اللغات.",
    "pricing.programs.eyebrow": "موجّه نحو الهدف",
    "pricing.programs.title": "برامج منظمة",
    "pricing.programs.subtitle": "لديك هدف محدد — درجة IELTS أو طلاقة مهنية? تتضمن هذه البرامج خارطة طريق واضحة وضمان نتائج.",
    "pricing.ielts.eyebrow": "تحضير IELTS",
    "pricing.ielts.title": "برنامج IELTS 8 أسابيع",
    "pricing.ielts.sessions": "2 جلسة/أسبوع · 16 جلسة إجمالاً",
    "pricing.ielts.desc": "16 جلسة خاصة على مدى 8 أسابيع، مخصصة كلياً لـ IELTS. جميع الأقسام الأربعة مع اختبارات تدريبية وتغذية راجعة مفصلة كل أسبوع.",
    "pricing.ielts.f1": "16 × جلسة خاصة لمدة ساعة",
    "pricing.ielts.f2": "جميع أقسام IELTS الأربعة: استماع، قراءة، كتابة، تحدث",
    "pricing.ielts.f3": "خطة دراسة IELTS مخصصة",
    "pricing.ielts.f4": "اختبارات تجريبية مع تغذية راجعة على الدرجة",
    "pricing.ielts.f5": "دعم واتساب طوال البرنامج",
    "pricing.ielts.f6": "ضمان النتائج مشمول",
    "pricing.business.eyebrow": "إنجليزية الأعمال",
    "pricing.business.title": "إنجليزية الأعمال 12 أسبوعاً",
    "pricing.business.sessions": "2 جلسة/أسبوع · 24 جلسة إجمالاً",
    "pricing.business.desc": "24 جلسة خاصة على مدى 12 أسبوعاً، مخصصة للإنجليزية المهنية. أتقن البريد الإلكتروني والاجتماعات والعروضات والمفردات المهنية.",
    "pricing.business.f1": "24 × جلسة خاصة لمدة ساعة",
    "pricing.business.f2": "منهج التواصل المهني",
    "pricing.business.f3": "كتابة البريد الإلكتروني المهني",
    "pricing.business.f4": "إنجليزية الاجتماعات والتفاوض",
    "pricing.business.f5": "تدريب على العروضات",
    "pricing.business.f6": "دعم واتساب طوال البرنامج",
    "pricing.included.title": "ما تتضمنه كل جلسة",
    "pricing.included.goal.title": "تدريب موجّه نحو الهدف",
    "pricing.included.goal.desc": "كل جلسة مبنية حول هدفك المحدد — IELTS أو الأعمال أو الطلاقة.",
    "pricing.included.feedback.title": "تغذية راجعة فورية",
    "pricing.included.feedback.desc": "تصحيحات فورية على النطق والقواعد والمفردات أثناء حديثك.",
    "pricing.included.whatsapp.title": "دعم واتساب",
    "pricing.included.whatsapp.desc": "اطرح أسئلتك واحصل على تغذية راجعة بين الجلسات، في أي وقت.",
    "pricing.included.progress.title": "تتبع التقدم",
    "pricing.included.progress.desc": "تقارير شهرية توضح بالضبط مدى تقدمك وما هو تالي.",
    "pricing.testimonials.title": "ماذا يقول الطلاب",
    "pricing.faq.title": "أسئلة شائعة",
    "pricing.cta.guarantee": "النتائج مضمونة — أو ندربك مجاناً",
    "pricing.cta.title": "غير متأكد من الخطة المناسبة لك;",
    "pricing.cta.subtitle": "احجز مكالمة مجانية لمدة 10 دقائق مع الأستاذ إبراهيم. سيستمع إلى أهدافك ويوصي بالخطة المناسبة.",
    "pricing.cta.urgency": "⏳ 3 أماكن فقط متاحة هذا الشهر — قد ترتفع الأسعار في أبريل",
    "pricing.cta.button": "احجز مكالمة استراتيجية مجانية",
    "pricing.cta.freeTest": "خذ اختبار المستوى المجاني أولاً",

    // ── Courses (extended) ──
    "courses.grid.title": "اختر برنامجك",
    "courses.grid.subtitle": "غير متأكد من البرنامج المناسب لك? اجرِ اختبار المستوى المجاني أو احجز مكالمة استراتيجية مجانية.",
    "courses.card.whoFor": "لمن هذا البرنامج",
    "courses.card.achieve": "ما ستحققه",
    "courses.card.program": "البرنامج",
    "courses.sessions.title": "ما تتضمنه كل جلسة",
    "courses.sessions.focus.title": "تركيز مخصص",
    "courses.sessions.focus.desc": "كل جلسة مبنية حول أهدافك ومستواك والتحديات التي تواجهها كمتعلم مغربي.",
    "courses.sessions.progress.title": "تتبع التقدم",
    "courses.sessions.progress.desc": "معالم واضحة ومتابعة منتظمة حتى تعرف دائماً بالضبط مدى تقدمك.",
    "courses.sessions.schedule.title": "جدولة مرنة",
    "courses.sessions.schedule.desc": "جلسات عبر Google Meet. إعادة الجدولة حتى 24 ساعة مسبقاً. وقتك، وتيرتك.",
    "courses.testimonials.title": "نتائج الطلاب",
    "courses.cta.freeTest": "اجرِ اختبار المستوى المجاني",
    "courses.cta.bookCall": "احجز مكالمة استراتيجية مجانية",

    // ── Free Test ──
    "freeTest.title": "اختبار مستوى الإنجليزية المجاني",
    "freeTest.subtitle": "اكتشف مستواك الدقيق في اللغة الإنجليزية في 10 دقائق. احصل على تقرير شخصي مع توصيات.",
    "freeTest.start": "ابدأ الاختبار المجاني",

    // ── Success Stories ──
    "success.title": "قصص نجاح الطلاب",
    "success.subtitle": "نتائج حقيقية من طلاب مغاربة حقيقيين حوّلوا لغتهم الإنجليزية.",

    // ── Free Resources ──
    "resources.title": "موارد الإنجليزية المجانية",
    "resources.subtitle": "تمارين وأدلة وأدوات لمساعدتك على تحسين إنجليزيتك — مجاناً تماماً.",

    // ── Common ──
    "common.learnMore": "اعرف المزيد",
    "common.bookCall": "احجز مكالمة استراتيجية مجانية",
    "common.freeCall": "مكالمة مجانية 10 دقائق · بدون التزام",
    "common.whatsapp": "واتساب",
    "common.readMore": "اقرأ المزيد",
    "common.viewAll": "عرض الكل",
    "common.download": "تحميل مجاني",
    "common.startNow": "ابدأ الآن",
    "common.perMonth": "/شهر",
    "common.perHour": "/ساعة",
    "common.save": "وفر",

    // ── Testimonials ──
    "testimonials.title": "موثوق به من طلاب عبر المغرب",
    "testimonials.subtitle": "قصص حقيقية ونتائج حقيقية من طلاب حوّلوا إنجليزيتهم مع Fluentry.",
    "testimonials.1.name": "فاطمة ز.",
    "testimonials.1.location": "طالبة IELTS، الدار البيضاء",
    "testimonials.1.quote": "غيّر تدريب إبراهيم طريقتي في تعلم الإنجليزية كلياً. انتقلت من ترجمة كل كلمة إلى التفكير مباشرةً بالإنجليزية. تحسّنت درجتي في IELTS بمقدار 1.5 نقطة!",
    "testimonials.2.name": "يوسف ب.",
    "testimonials.2.location": "مدير تسويق، الرباط",
    "testimonials.2.quote": "كنت بحاجة إلى تحسين مهارات العروض بسرعة. أعطاني كورس إنجليزية الأعمال الثقة لإدارة اجتماعات دولية.",
    "testimonials.3.name": "أمينة ك.",
    "testimonials.3.location": "طالبة جامعية، طنجة",
    "testimonials.3.quote": "الموارد المجانية رائعة! دليل التعابير الاصطلاحية وتمارين الاستماع ساعدتني كثيراً. إنه أفضل مكان لتعلم الإنجليزية في المغرب.",
    "testimonials.4.name": "مهدي ل.",
    "testimonials.4.location": "مطوّر برمجيات، مراكش",
    "testimonials.4.quote": "كنت عالقاً عند مستوى متوسط لسنوات. ساعدتني الجلسات الفردية على تجاوز هذا الحاجز. أستطيع الآن التعبير عن أفكار معقدة بوضوح.",
    "testimonials.5.name": "سلمى ج.",
    "testimonials.5.location": "طالبة TOEFL، فاس",
    "testimonials.5.quote": "كانت ممارسة التحدث لا تقدّر بثمن. الأستاذ إبراهيم صبور ويعرف بالضبط كيف يصحح نطق الناطقين بالعربية. حصلت على 28/30 في قسم التحدث في TOEFL!",

    // ── Newsletter ──
    "newsletter.title": "احصل على نصائح إنجليزية أسبوعياً",
    "newsletter.subtitle": "انضم إلى مئات الطلاب الذين يتلقّون نصائح تعلم مجانية وشرح قواعد اللغة واستراتيجيات الدراسة كل أسبوع.",
    "newsletter.placeholder": "أدخل بريدك الإلكتروني",
    "newsletter.button": "اشترك مجاناً",
    "newsletter.subscribing": "جاري الاشتراك...",
    "newsletter.disclaimer": "لا بريد عشوائي. إلغاء الاشتراك في أي وقت. مجاني 100% للأبد.",
    "newsletter.error": "يرجى إدخال عنوان بريد إلكتروني صحيح",
    "newsletter.success": "شكراً على اشتراكك! تحقّق من بريدك الإلكتروني للتأكيد.",

    // ── Blog posts (Home) ──
    "home.blog.post1.title": "دروس الإنجليزية عبر الإنترنت للمغاربة",
    "home.blog.post1.excerpt": "قارن الأسعار والطرق لإيجاد أفضل طريقة لتعلم الإنجليزية عبر الإنترنت.",
    "home.blog.post1.category": "دليل تعلم",
    "home.blog.post1.readTime": "12 دقيقة",
    "home.blog.post2.title": "من A2 إلى B1 في 6 أشهر",
    "home.blog.post2.excerpt": "خطة عملية لمدة 6 أشهر مع جدول أسبوعي لتحسين إنجليزيتك.",
    "home.blog.post2.category": "خطة تعلم",
    "home.blog.post2.readTime": "10 دقائق",
    "home.blog.post3.title": "أفضل 15 تطبيقاً لتعلم الإنجليزية",
    "home.blog.post3.excerpt": "اكتشف أفضل الأدوات الرقمية للمفردات والاستماع والقراءة.",
    "home.blog.post3.category": "مراجعة أدوات",
    "home.blog.post3.readTime": "14 دقيقة",
    "home.blog.post4.title": "5 تحديات يواجهها المتعلمون المغاربة",
    "home.blog.post4.excerpt": "افهم العقبات الفريدة والحلول العملية للمتعلمين المغاربة.",
    "home.blog.post4.category": "رؤى تعليمية",
    "home.blog.post4.readTime": "11 دقيقة",
  },
};

// ─── Provider ────────────────────────────────────────────────────────────────

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [location, setLocation] = useLocation();

  // Derive language from URL
  const lang: Language = getLangFromPath(location);
  const isRTL = lang === "ar";
  const langPrefix = `/${lang}`;

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    if (isRTL) {
      document.documentElement.classList.add("rtl");
    } else {
      document.documentElement.classList.remove("rtl");
    }
  }, [lang, isRTL]);

  const setLang = (newLang: Language) => {
    const currentPath = stripLangPrefix(location);
    setLocation(`/${newLang}${currentPath === "/" ? "" : currentPath}`);
  };

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL, langPrefix }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ─── Hook ────────────────────────────────────────────────────────────────────

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
